"""Unit tests for VaultService.

Covers every public method in workspace.passwords.services.vault:
  - generate_kdf_salt
  - create_vault
  - list_vaults
  - get_vault
  - setup_vault
  - verify_unlock
  - accessible_entries_q
  - get_login_entries
  - delete_vault
"""

import uuid

from django.contrib.auth import get_user_model
from django.test import TestCase
from django.utils import timezone
from rest_framework.test import APIClient

from workspace.passwords.models import LoginEntry, PasswordEntry, Vault, VaultMember
from workspace.passwords.services.vault import VaultService

User = get_user_model()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

class VaultServiceMixin:
    """Create two independent users for each test."""

    def setUp(self):
        self.alice = User.objects.create_user(username='alice_vs', email='alice@test.com', password='pass')
        self.bob = User.objects.create_user(username='bob_vs', email='bob@test.com', password='pass')

    def _setup_vault(self, user, name='Personal', client_hash='hash-abc') -> Vault:
        """Create and fully set up a vault. kdf_salt is server-generated by create_vault."""
        vault = VaultService.create_vault(user, name=name)
        return VaultService.setup_vault(
            vault=vault,
            client_master_hash=client_hash,
            protected_vault_key='encrypted-vault-key',
        )

    def _make_entry(self, user, vault=None, deleted=False) -> LoginEntry:
        if vault is None:
            vault = VaultService.create_vault(user)
        entry = LoginEntry.objects.create(
            vault=vault,
            encrypted_name='enc-name',
            type=PasswordEntry.EntryType.LOGIN,
        )
        if deleted:
            entry.deleted_at = timezone.now()
            entry.save(update_fields=['deleted_at'])
        return entry

    def _shared_vault(self, owner, member, role=VaultMember.Role.VIEWER) -> Vault:
        """Create a vault owned by *owner* and give *member* accepted access."""
        vault = VaultService.create_vault(owner, name='Shared')
        VaultMember.objects.create(
            vault=vault,
            user=member,
            role=role,
            status=VaultMember.Status.ACCEPTED,
            protected_vault_key='enc-key-for-member',
        )
        return vault


# ---------------------------------------------------------------------------
# generate_kdf_salt
# ---------------------------------------------------------------------------

class GenerateKdfSaltTests(VaultServiceMixin, TestCase):

    def test_returns_nonempty_string(self):
        salt = VaultService.generate_kdf_salt(self.alice)
        self.assertTrue(salt)
        self.assertIsInstance(salt, str)

    def test_salt_fits_in_field(self):
        salt = VaultService.generate_kdf_salt(self.alice)
        self.assertLessEqual(len(salt), 44)

    def test_salts_are_unique_per_call(self):
        s1 = VaultService.generate_kdf_salt(self.alice)
        s2 = VaultService.generate_kdf_salt(self.alice)
        self.assertNotEqual(s1, s2)

    def test_salts_differ_across_users(self):
        # Salts for different users differ (with overwhelming probability)
        sa = VaultService.generate_kdf_salt(self.alice)
        sb = VaultService.generate_kdf_salt(self.bob)
        self.assertNotEqual(sa, sb)

    def test_salt_is_base64url_compatible(self):
        import base64
        salt = VaultService.generate_kdf_salt(self.alice)
        # Should decode without error (add padding if needed)
        padded = salt + '=' * (-len(salt) % 4)
        decoded = base64.urlsafe_b64decode(padded)
        self.assertEqual(len(decoded), 32)


# ---------------------------------------------------------------------------
# create_vault
# ---------------------------------------------------------------------------

class CreateVaultTests(VaultServiceMixin, TestCase):

    def test_creates_vault_with_defaults(self):
        vault = VaultService.create_vault(self.alice)
        self.assertIsInstance(vault, Vault)
        self.assertEqual(vault.user, self.alice)
        self.assertEqual(vault.name, 'Personal')

    def test_creates_vault_with_custom_name(self):
        vault = VaultService.create_vault(self.alice, name='Work')
        self.assertEqual(vault.name, 'Work')

    def test_new_vault_is_not_setup(self):
        vault = VaultService.create_vault(self.alice)
        self.assertFalse(vault.is_setup)

    def test_pregenerates_kdf_salt(self):
        vault = VaultService.create_vault(self.alice)
        self.assertTrue(vault.kdf_salt)
        self.assertLessEqual(len(vault.kdf_salt), 44)

    def test_each_vault_gets_unique_kdf_salt(self):
        v1 = VaultService.create_vault(self.alice, name='Personal')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self.assertNotEqual(v1.kdf_salt, v2.kdf_salt)

    def test_multiple_vaults_per_user(self):
        v1 = VaultService.create_vault(self.alice, name='Personal')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self.assertNotEqual(v1.pk, v2.pk)
        self.assertEqual(Vault.objects.filter(user=self.alice).count(), 2)

    def test_vaults_are_isolated_per_user(self):
        va = VaultService.create_vault(self.alice)
        vb = VaultService.create_vault(self.bob)
        self.assertNotEqual(va.pk, vb.pk)
        self.assertEqual(va.user, self.alice)
        self.assertEqual(vb.user, self.bob)

    def test_vault_is_persisted(self):
        vault = VaultService.create_vault(self.alice, name='Saved')
        from_db = Vault.objects.get(pk=vault.pk)
        self.assertEqual(from_db.name, 'Saved')


# ---------------------------------------------------------------------------
# list_vaults
# ---------------------------------------------------------------------------

class ListVaultsTests(VaultServiceMixin, TestCase):

    def test_returns_empty_queryset_when_no_vaults(self):
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 0)

    def test_returns_all_owned_vaults(self):
        VaultService.create_vault(self.alice, name='Personal')
        VaultService.create_vault(self.alice, name='Work')
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 2)

    def test_excludes_other_users_vaults(self):
        VaultService.create_vault(self.bob)
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 0)

    def test_isolation_is_symmetric(self):
        VaultService.create_vault(self.alice)
        VaultService.create_vault(self.bob)
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 1)
        self.assertEqual(VaultService.list_vaults(self.bob).count(), 1)

    def test_includes_shared_vault_with_accepted_membership(self):
        vault = self._shared_vault(self.bob, self.alice)
        pks = list(VaultService.list_vaults(self.alice).values_list('pk', flat=True))
        self.assertIn(vault.pk, pks)

    def test_excludes_shared_vault_with_pending_membership(self):
        bob_vault = VaultService.create_vault(self.bob)
        VaultMember.objects.create(
            vault=bob_vault, user=self.alice, role=VaultMember.Role.VIEWER,
            status=VaultMember.Status.PENDING, protected_vault_key='pk',
        )
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 0)

    def test_excludes_shared_vault_with_revoked_membership(self):
        bob_vault = VaultService.create_vault(self.bob)
        VaultMember.objects.create(
            vault=bob_vault, user=self.alice, role=VaultMember.Role.VIEWER,
            status=VaultMember.Status.REVOKED, protected_vault_key='pk',
        )
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 0)

    def test_own_vault_not_duplicated_when_member_exists(self):
        # Regression: owner should appear once even if they have a VaultMember row
        alice_vault = VaultService.create_vault(self.alice)
        VaultMember.objects.create(
            vault=alice_vault, user=self.bob, role=VaultMember.Role.VIEWER,
            status=VaultMember.Status.ACCEPTED, protected_vault_key='pk',
        )
        self.assertEqual(VaultService.list_vaults(self.alice).count(), 1)


# ---------------------------------------------------------------------------
# get_vault
# ---------------------------------------------------------------------------

class GetVaultTests(VaultServiceMixin, TestCase):

    def test_returns_own_vault(self):
        vault = VaultService.create_vault(self.alice)
        result = VaultService.get_vault(self.alice, vault.pk)
        self.assertEqual(result.pk, vault.pk)

    def test_returns_none_for_nonexistent_uuid(self):
        self.assertIsNone(VaultService.get_vault(self.alice, uuid.uuid4()))

    def test_returns_none_for_other_users_vault(self):
        bob_vault = VaultService.create_vault(self.bob)
        self.assertIsNone(VaultService.get_vault(self.alice, bob_vault.pk))

    def test_returns_correct_vault_among_many(self):
        v1 = VaultService.create_vault(self.alice, name='Personal')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self.assertEqual(VaultService.get_vault(self.alice, v2.pk).pk, v2.pk)
        self.assertEqual(VaultService.get_vault(self.alice, v1.pk).pk, v1.pk)

    def test_returns_shared_vault_with_accepted_membership(self):
        vault = self._shared_vault(self.bob, self.alice)
        result = VaultService.get_vault(self.alice, vault.pk)
        self.assertIsNotNone(result)
        self.assertEqual(result.pk, vault.pk)

    def test_returns_none_for_shared_vault_with_pending_membership(self):
        bob_vault = VaultService.create_vault(self.bob)
        VaultMember.objects.create(
            vault=bob_vault, user=self.alice, role=VaultMember.Role.VIEWER,
            status=VaultMember.Status.PENDING, protected_vault_key='pk',
        )
        self.assertIsNone(VaultService.get_vault(self.alice, bob_vault.pk))

    def test_returns_none_for_shared_vault_with_revoked_membership(self):
        bob_vault = VaultService.create_vault(self.bob)
        VaultMember.objects.create(
            vault=bob_vault, user=self.alice, role=VaultMember.Role.VIEWER,
            status=VaultMember.Status.REVOKED, protected_vault_key='pk',
        )
        self.assertIsNone(VaultService.get_vault(self.alice, bob_vault.pk))


# ---------------------------------------------------------------------------
# setup_vault
# ---------------------------------------------------------------------------

class SetupVaultTests(VaultServiceMixin, TestCase):

    def test_marks_vault_as_setup(self):
        vault = self._setup_vault(self.alice)
        self.assertTrue(vault.is_setup)

    def test_stores_protected_vault_key(self):
        vault = self._setup_vault(self.alice)
        self.assertEqual(vault.protected_vault_key, 'encrypted-vault-key')

    def test_preserves_server_generated_kdf_salt(self):
        vault = VaultService.create_vault(self.alice)
        original_salt = vault.kdf_salt
        VaultService.setup_vault(vault=vault, client_master_hash='h', protected_vault_key='k')
        vault.refresh_from_db()
        self.assertEqual(vault.kdf_salt, original_salt)

    def test_rotation_can_replace_kdf_salt(self):
        vault = self._setup_vault(self.alice)
        new_salt = 'B' * 43
        VaultService.setup_vault(
            vault=vault, client_master_hash='new', protected_vault_key='new-key',
            kdf_salt=new_salt,
        )
        vault.refresh_from_db()
        self.assertEqual(vault.kdf_salt, new_salt)

    def test_master_password_hash_is_not_stored_raw(self):
        vault = self._setup_vault(self.alice, client_hash='my-secret-hash')
        self.assertNotEqual(vault.master_password_hash, 'my-secret-hash')
        self.assertTrue(vault.master_password_hash)

    def test_optional_kdf_algorithm_is_updated(self):
        vault = VaultService.create_vault(self.alice)
        VaultService.setup_vault(
            vault=vault,
            client_master_hash='h',
            protected_vault_key='k',
            kdf_algorithm=Vault.KdfAlgorithm.ARGON2ID,
            kdf_memory=65536,
            kdf_parallelism=4,
        )
        vault.refresh_from_db()
        self.assertEqual(vault.kdf_algorithm, Vault.KdfAlgorithm.ARGON2ID)
        self.assertEqual(vault.kdf_memory, 65536)
        self.assertEqual(vault.kdf_parallelism, 4)

    def test_optional_kdf_iterations_is_updated(self):
        vault = VaultService.create_vault(self.alice)
        VaultService.setup_vault(
            vault=vault, client_master_hash='h', protected_vault_key='k',
            kdf_iterations=800_000,
        )
        vault.refresh_from_db()
        self.assertEqual(vault.kdf_iterations, 800_000)

    def test_setup_is_persisted_to_db(self):
        vault = self._setup_vault(self.alice)
        from_db = Vault.objects.get(pk=vault.pk)
        self.assertTrue(from_db.is_setup)
        self.assertTrue(from_db.protected_vault_key)

    def test_rotation_replaces_existing_protected_key(self):
        vault = self._setup_vault(self.alice, client_hash='old-hash')
        VaultService.setup_vault(
            vault=vault,
            client_master_hash='new-hash',
            protected_vault_key='new-encrypted-key',
        )
        vault.refresh_from_db()
        self.assertEqual(vault.protected_vault_key, 'new-encrypted-key')

    def test_each_vault_has_independent_setup(self):
        v1 = self._setup_vault(self.alice, name='Personal', client_hash='hash-1')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self.assertTrue(v1.is_setup)
        self.assertFalse(v2.is_setup)


# ---------------------------------------------------------------------------
# verify_unlock
# ---------------------------------------------------------------------------

class VerifyUnlockTests(VaultServiceMixin, TestCase):

    def test_returns_true_and_key_on_correct_hash(self):
        vault = self._setup_vault(self.alice, client_hash='correct-hash')
        ok, key = VaultService.verify_unlock(vault, 'correct-hash')
        self.assertTrue(ok)
        self.assertEqual(key, 'encrypted-vault-key')

    def test_returns_false_on_wrong_hash(self):
        vault = self._setup_vault(self.alice, client_hash='correct-hash')
        ok, key = VaultService.verify_unlock(vault, 'wrong-hash')
        self.assertFalse(ok)
        self.assertEqual(key, '')

    def test_returns_false_when_vault_not_setup(self):
        vault = VaultService.create_vault(self.alice)
        ok, key = VaultService.verify_unlock(vault, 'any-hash')
        self.assertFalse(ok)
        self.assertEqual(key, '')

    def test_empty_hash_does_not_unlock(self):
        vault = self._setup_vault(self.alice, client_hash='real-hash')
        ok, key = VaultService.verify_unlock(vault, '')
        self.assertFalse(ok)
        self.assertEqual(key, '')

    def test_unlock_is_per_vault(self):
        v1 = self._setup_vault(self.alice, name='Personal', client_hash='hash-1')
        v2 = self._setup_vault(self.alice, name='Work', client_hash='hash-2')
        ok1, _ = VaultService.verify_unlock(v1, 'hash-1')
        ok2, _ = VaultService.verify_unlock(v2, 'hash-1')  # wrong hash for v2
        self.assertTrue(ok1)
        self.assertFalse(ok2)


# ---------------------------------------------------------------------------
# accessible_entries_q
# ---------------------------------------------------------------------------

class AccessibleEntriesQTests(VaultServiceMixin, TestCase):

    def test_user_can_access_own_entries(self):
        self._make_entry(self.alice)
        q = VaultService.accessible_entries_q(self.alice)
        self.assertEqual(LoginEntry.objects.filter(q).count(), 1)

    def test_user_cannot_access_other_users_entries(self):
        self._make_entry(self.bob)
        q = VaultService.accessible_entries_q(self.alice)
        self.assertEqual(LoginEntry.objects.filter(q).count(), 0)

    def test_isolation_is_symmetric(self):
        self._make_entry(self.alice)
        self._make_entry(self.bob)
        self.assertEqual(LoginEntry.objects.filter(VaultService.accessible_entries_q(self.alice)).count(), 1)
        self.assertEqual(LoginEntry.objects.filter(VaultService.accessible_entries_q(self.bob)).count(), 1)

    def test_entries_across_multiple_vaults_are_accessible(self):
        v1 = VaultService.create_vault(self.alice, name='Personal')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self._make_entry(self.alice, vault=v1)
        self._make_entry(self.alice, vault=v2)
        q = VaultService.accessible_entries_q(self.alice)
        self.assertEqual(LoginEntry.objects.filter(q).count(), 2)

    def test_includes_entries_from_shared_vault(self):
        vault = self._shared_vault(self.bob, self.alice)
        self._make_entry(self.bob, vault=vault)
        q = VaultService.accessible_entries_q(self.alice)
        self.assertEqual(LoginEntry.objects.filter(q).distinct().count(), 1)

    def test_excludes_entries_from_pending_shared_vault(self):
        bob_vault = VaultService.create_vault(self.bob)
        VaultMember.objects.create(
            vault=bob_vault, user=self.alice, role=VaultMember.Role.VIEWER,
            status=VaultMember.Status.PENDING, protected_vault_key='pk',
        )
        self._make_entry(self.bob, vault=bob_vault)
        q = VaultService.accessible_entries_q(self.alice)
        self.assertEqual(LoginEntry.objects.filter(q).count(), 0)


# ---------------------------------------------------------------------------
# get_login_entries
# ---------------------------------------------------------------------------

class GetLoginEntriesTests(VaultServiceMixin, TestCase):

    def test_returns_own_active_entries(self):
        self._make_entry(self.alice)
        self.assertEqual(VaultService.get_login_entries(self.alice).count(), 1)

    def test_excludes_deleted_by_default(self):
        self._make_entry(self.alice)
        self._make_entry(self.alice, deleted=True)
        self.assertEqual(VaultService.get_login_entries(self.alice).count(), 1)

    def test_include_deleted_returns_all(self):
        self._make_entry(self.alice)
        self._make_entry(self.alice, deleted=True)
        self.assertEqual(VaultService.get_login_entries(self.alice, include_deleted=True).count(), 2)

    def test_excludes_other_users_entries(self):
        self._make_entry(self.bob)
        self.assertEqual(VaultService.get_login_entries(self.alice).count(), 0)

    def test_vault_uuid_filter(self):
        v1 = VaultService.create_vault(self.alice, name='Personal')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self._make_entry(self.alice, vault=v1)
        self._make_entry(self.alice, vault=v2)
        qs = VaultService.get_login_entries(self.alice, vault_uuid=v1.pk)
        self.assertEqual(qs.count(), 1)
        self.assertEqual(qs.first().vault_id, v1.pk)

    def test_vault_uuid_filter_excludes_other_vault(self):
        v1 = VaultService.create_vault(self.alice, name='Personal')
        v2 = VaultService.create_vault(self.alice, name='Work')
        self._make_entry(self.alice, vault=v2)
        self.assertEqual(VaultService.get_login_entries(self.alice, vault_uuid=v1.pk).count(), 0)

    def test_vault_uuid_of_other_user_returns_empty(self):
        bob_vault = VaultService.create_vault(self.bob)
        self._make_entry(self.bob, vault=bob_vault)
        self.assertEqual(VaultService.get_login_entries(self.alice, vault_uuid=bob_vault.pk).count(), 0)

    def test_returns_entries_from_shared_vault(self):
        vault = self._shared_vault(self.bob, self.alice)
        self._make_entry(self.bob, vault=vault)
        self.assertEqual(VaultService.get_login_entries(self.alice).count(), 1)

    def test_empty_when_no_entries(self):
        self.assertEqual(VaultService.get_login_entries(self.alice).count(), 0)


# ---------------------------------------------------------------------------
# delete_vault
# ---------------------------------------------------------------------------

class DeleteVaultTests(VaultServiceMixin, TestCase):

    def test_owner_can_delete_vault(self):
        vault = VaultService.create_vault(self.alice)
        vault_pk = vault.pk
        result = VaultService.delete_vault(self.alice, vault_pk)
        self.assertTrue(result)
        self.assertFalse(Vault.objects.filter(pk=vault_pk).exists())

    def test_non_owner_cannot_delete_vault(self):
        vault = VaultService.create_vault(self.alice)
        vault_pk = vault.pk
        result = VaultService.delete_vault(self.bob, vault_pk)
        self.assertFalse(result)
        self.assertTrue(Vault.objects.filter(pk=vault_pk).exists())

    def test_manager_member_cannot_delete_vault(self):
        vault = self._shared_vault(self.alice, self.bob, role=VaultMember.Role.MANAGER)
        vault_pk = vault.pk
        result = VaultService.delete_vault(self.bob, vault_pk)
        self.assertFalse(result)
        self.assertTrue(Vault.objects.filter(pk=vault_pk).exists())

    def test_delete_cascades_entries(self):
        vault = VaultService.create_vault(self.alice)
        entry = self._make_entry(self.alice, vault=vault)
        entry_pk = entry.pk
        result = VaultService.delete_vault(self.alice, vault.pk)
        self.assertTrue(result)
        self.assertEqual(LoginEntry.objects.filter(pk=entry_pk).count(), 0)

    def test_delete_cascades_members(self):
        vault = self._shared_vault(self.alice, self.bob)
        member = VaultMember.objects.filter(vault=vault).first()
        member_pk = member.pk
        result = VaultService.delete_vault(self.alice, vault.pk)
        self.assertTrue(result)
        self.assertEqual(VaultMember.objects.filter(pk=member_pk).count(), 0)

    def test_delete_nonexistent_vault_returns_false(self):
        result = VaultService.delete_vault(self.alice, uuid.uuid4())
        self.assertFalse(result)


# ---------------------------------------------------------------------------
# DELETE /api/v1/passwords/vaults/<uuid> — View layer tests
# ---------------------------------------------------------------------------

class DeleteVaultViewTests(VaultServiceMixin, TestCase):

    def setUp(self):
        super().setUp()
        self.client = APIClient()

    def test_owner_gets_204(self):
        vault = VaultService.create_vault(self.alice)
        self.client.force_authenticate(user=self.alice)
        response = self.client.delete(f'/api/v1/passwords/vaults/{vault.pk}')
        self.assertEqual(response.status_code, 204)
        self.assertFalse(Vault.objects.filter(pk=vault.pk).exists())

    def test_member_gets_404(self):
        vault = self._shared_vault(self.alice, self.bob)
        self.client.force_authenticate(user=self.bob)
        response = self.client.delete(f'/api/v1/passwords/vaults/{vault.pk}')
        self.assertEqual(response.status_code, 404)
        self.assertTrue(Vault.objects.filter(pk=vault.pk).exists())

    def test_unauthenticated_gets_403(self):
        vault = VaultService.create_vault(self.alice)
        response = self.client.delete(f'/api/v1/passwords/vaults/{vault.pk}')
        self.assertEqual(response.status_code, 403)
        self.assertTrue(Vault.objects.filter(pk=vault.pk).exists())

    def test_nonexistent_vault_gets_404(self):
        self.client.force_authenticate(user=self.alice)
        response = self.client.delete(f'/api/v1/passwords/vaults/{uuid.uuid4()}')
        self.assertEqual(response.status_code, 404)
