# Generated by Django 6.0.2 on 2026-02-10 19:51

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('auth_method', models.CharField(choices=[('password', 'Password'), ('oauth2', 'OAuth2')], default='password', max_length=10)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('oauth2_provider', models.CharField(blank=True, default='', max_length=50)),
                ('oauth2_data_encrypted', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='MailFolder',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('folder_type', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash'), ('spam', 'Spam'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=10)),
                ('uid_validity', models.BigIntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_sync_uid', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mail.mailaccount')),
            ],
            options={
                'ordering': ['account', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, default='', max_length=512)),
                ('imap_uid', models.BigIntegerField()),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('from_address', models.JSONField(default=dict)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(default=list)),
                ('bcc_addresses', models.JSONField(default=list)),
                ('reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, default='', max_length=300)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailaccount')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailfolder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('content', models.FileField(upload_to='mail/attachments/')),
                ('content_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_inline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mailmessage')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.AddConstraint(
            model_name='mailfolder',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_mail_folder'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['folder', '-date'], name='mail_mailme_folder__d0c487_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', 'message_id'], name='mail_mailme_account_f21d07_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['folder', 'imap_uid'], name='mail_mailme_folder__7eb03e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailmessage',
            constraint=models.UniqueConstraint(fields=('folder', 'imap_uid'), name='unique_mail_message_uid'),
        ),
    ]
