# Generated by Django 6.0.2 on 2026-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailfolder',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mailfolder',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
