# Generated by Django 6.0.2 on 2026-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mailfolder_color_mailfolder_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='imap_delimiter',
            field=models.CharField(default='/', max_length=5),
        ),
    ]
