# Generated by Django 6.0.2 on 2026-02-15 08:57

import workspace.mail.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mailaccount_imap_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailattachment',
            name='content',
            field=models.FileField(upload_to=workspace.mail.models.mail_attachment_path),
        ),
    ]
