# Generated by Django 6.0.2 on 2026-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_attachment_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='has_calendar_event',
            field=models.BooleanField(default=False),
        ),
    ]
