# Generated by Django 6.0.2 on 2026-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_mailmessage_has_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailfolder',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
