# Generated by Django 6.0.2 on 2026-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_mailfolder_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
