# Generated by Django 6.0.3 on 2026-03-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_add_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('action', 'Action required'), ('fyi', 'FYI'), ('newsletter', 'Newsletter'), ('notification', 'Notification')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['folder', 'ai_category'], name='mail_mailme_folder__1324a9_idx'),
        ),
    ]
