# Generated by Django 6.0.3 on 2026-03-13 18:20

import django.db.models.deletion
from django.db import migrations, models

import workspace.common.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_add_ai_classification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLabel',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='mail.mailaccount')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MailMessageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_links', to='mail.maillabel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_labels', to='mail.mailmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='maillabel',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_mail_label_per_account'),
        ),
        migrations.AddConstraint(
            model_name='mailmessagelabel',
            constraint=models.UniqueConstraint(fields=('message', 'label'), name='unique_mail_message_label'),
        ),
    ]
