# Generated by Django 6.0.3 on 2026-03-13 18:22

from django.db import migrations

DEFAULT_LABELS = [
    {'name': 'Urgent', 'color': 'error', 'icon': 'alert-triangle', 'position': 0},
    {'name': 'Action', 'color': 'warning', 'icon': 'check-circle', 'position': 1},
    {'name': 'FYI', 'color': 'info', 'icon': 'info', 'position': 2},
    {'name': 'Newsletter', 'color': 'secondary', 'icon': 'newspaper', 'position': 3},
    {'name': 'Notification', 'color': 'ghost', 'icon': 'bell', 'position': 4},
]

CATEGORY_TO_LABEL = {
    'urgent': 'Urgent',
    'action': 'Action',
    'fyi': 'FYI',
    'newsletter': 'Newsletter',
    'notification': 'Notification',
}


def seed_and_migrate(apps, schema_editor):
    MailAccount = apps.get_model('mail', 'MailAccount')
    MailLabel = apps.get_model('mail', 'MailLabel')
    MailMessage = apps.get_model('mail', 'MailMessage')
    MailMessageLabel = apps.get_model('mail', 'MailMessageLabel')

    # Seed default labels for all existing accounts
    for account in MailAccount.objects.all():
        existing_names = set(account.labels.values_list('name', flat=True))
        to_create = [
            MailLabel(account=account, **lbl)
            for lbl in DEFAULT_LABELS
            if lbl['name'] not in existing_names
        ]
        if to_create:
            MailLabel.objects.bulk_create(to_create)

    # Migrate ai_category → MailMessageLabel
    for cat_value, label_name in CATEGORY_TO_LABEL.items():
        messages = MailMessage.objects.filter(ai_category=cat_value).select_related('account')
        links = []
        label_cache = {}
        for msg in messages.iterator():
            key = (msg.account_id, label_name)
            if key not in label_cache:
                label_cache[key] = MailLabel.objects.get(account_id=msg.account_id, name=label_name)
            links.append(MailMessageLabel(message=msg, label=label_cache[key]))
            if len(links) >= 1000:
                MailMessageLabel.objects.bulk_create(links, ignore_conflicts=True)
                links = []
        if links:
            MailMessageLabel.objects.bulk_create(links, ignore_conflicts=True)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('mail', '0009_add_label_models'),
    ]

    operations = [
        migrations.RunPython(seed_and_migrate, reverse_noop),
    ]
