# Generated by Django 6.0.3 on 2026-03-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_seed_labels_migrate_categories'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mailmessage',
            name='mail_mailme_folder__1324a9_idx',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='ai_tags',
        ),
    ]
