# Generated by Django 6.0.3 on 2026-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_remove_ai_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillabel',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
