# Generated by Django 6.0.3 on 2026-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_add_label_unread_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mailmessage',
            name='mail_mailme_folder__d0c487_idx',
        ),
        migrations.AddIndex(
            model_name='mailfolder',
            index=models.Index(fields=['account', 'folder_type'], name='mail_mailfo_account_8e683b_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['folder', 'deleted_at', '-date'], name='mail_mailme_folder__cdd222_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', 'deleted_at', '-date'], name='mail_mailme_account_51b991_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', 'is_starred', '-date'], name='mail_mailme_account_50a64a_idx'),
        ),
    ]
