# Generated by Django 6.0.4 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_perf_add_missing_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', 'is_read', 'deleted_at'], name='mail_acct_read_del'),
        ),
        migrations.AddIndex(
            model_name='mailmessagelabel',
            index=models.Index(fields=['label'], name='mail_msglabel_label'),
        ),
    ]
