# Generated by Django 6.0.4 on 2026-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_mailmessage_mail_acct_read_del_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mailmessage',
            name='mail_mailme_folder__7eb03e_idx',
        ),
    ]
