# Generated by Django 6.0.5 on 2026-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_drop_redundant_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
