# Generated by Django 6.0.5 on 2026-05-14 19:50

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mail', '0016_mailmessage_in_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailExtraction',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('event', 'Event')], max_length=32)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('dismissed', 'Dismissed')], default='detected', max_length=16)),
                ('target_object_id', models.UUIDField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, default='', max_length=8)),
                ('model_used', models.CharField(blank=True, default='', max_length=64)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='mail.mailmessage')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mail_message', 'kind'], name='mail_mailex_mail_me_bbcba5_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='mail_mailex_target__8b9ef9_idx')],
            },
        ),
    ]
