# Generated by Django 6.0.5 on 2026-05-18 18:31

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0017_mailextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRule',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('stop_processing', models.BooleanField(default=False)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mail.mailaccount')),
            ],
            options={
                'ordering': ['account', 'position', 'created_at'],
                'indexes': [models.Index(fields=['account', 'is_enabled', 'position'], name='mail_mailru_account_929416_idx')],
            },
        ),
    ]
