# Generated by Django 6.0.5 on 2026-05-18 18:33

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0018_mailrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailRuleLog',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('rule_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('actions_applied', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_logs', to='mail.mailmessage')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='mail.mailrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', '-created_at'], name='mail_mailru_message_d7291f_idx'), models.Index(fields=['rule', '-created_at'], name='mail_mailru_rule_id_d0bfb6_idx')],
            },
        ),
    ]
