# Generated by Django 6.0.6 on 2026-06-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0019_mailrulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailfolder',
            name='ai_classify_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
