# Generated by Django 6.0.6 on 2026-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0020_mailfolder_ai_classify_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
