# Generated by Django 6.0.7 on 2026-07-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0021_mailaccount_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='from_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='recipients_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
