# Generated by Django 6.0.7 on 2026-07-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0023_backfill_address_search_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='from_address',
        ),
    ]
