# Generated by Django 6.0.7 on 2026-07-25 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0027_rename_fts_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mailaccount',
            index=models.Index(fields=['is_active', 'last_sync_at'], name='mail_active_synced'),
        ),
    ]
