# Generated by Django 6.0.7 on 2026-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0028_mailaccount_mail_active_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
    ]
