# Generated by Django 6.0.7 on 2026-08-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0029_mailmessage_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillabel',
            name='notify_on_apply',
            field=models.BooleanField(default=False),
        ),
    ]
