# Generated by Django 6.0.7 on 2026-08-12 08:44

from django.db import migrations


def flag_urgent_labels(apps, schema_editor):
    MailLabel = apps.get_model("mail", "MailLabel")
    MailLabel.objects.using(schema_editor.connection.alias).filter(
        name__iexact="Urgent"
    ).update(notify_on_apply=True)


def unflag_urgent_labels(apps, schema_editor):
    MailLabel = apps.get_model("mail", "MailLabel")
    MailLabel.objects.using(schema_editor.connection.alias).filter(
        name__iexact="Urgent"
    ).update(notify_on_apply=False)


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0030_maillabel_notify_on_apply"),
    ]

    operations = [
        migrations.RunPython(flag_urgent_labels, unflag_urgent_labels),
    ]
