# Generated by Django 6.1 on 2026-08-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0032_seed_suspicious_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillabel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
