# Generated by Django 6.0.2 on 2026-02-11 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['owner', 'name'], name='cal_owner_name'),
        ),
        migrations.AddIndex(
            model_name='eventmember',
            index=models.Index(fields=['status'], name='evtmember_status'),
        ),
        migrations.AddIndex(
            model_name='eventmember',
            index=models.Index(fields=['user', 'status'], name='evtmember_user_status'),
        ),
    ]
