# Generated by Django 6.0.2 on 2026-02-11 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_add_missing_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='original_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['recurrence_parent', 'original_start'], name='calendar_ev_recurre_a1e87a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['recurrence_frequency', 'start'], name='calendar_ev_recurre_4cad78_idx'),
        ),
    ]
