# Generated by Django 6.0.2 on 2026-02-21 18:49

import django.db.models.deletion
import workspace.calendar.models
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_event_is_cancelled_event_original_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('share_token', models.CharField(default=workspace.calendar.models._generate_share_token, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calendar.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollSlot',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='calendar.poll')),
            ],
            options={
                'ordering': ['position', 'start'],
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='chosen_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calendar.pollslot'),
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='calendar.pollslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pollslot',
            index=models.Index(fields=['poll', 'position'], name='calendar_po_poll_id_95e910_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_by', 'status'], name='calendar_po_created_e1984a_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['share_token'], name='calendar_po_share_t_4033e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('slot', 'user'), name='unique_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('guest_name', ''), _negated=True)), fields=('slot', 'guest_name'), name='unique_vote_per_guest'),
        ),
    ]
