# Generated by Django 6.0.2 on 2026-02-21 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_poll_pollslot_poll_chosen_slot_pollvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pollvote',
            name='unique_vote_per_guest',
        ),
        migrations.AddField(
            model_name='pollvote',
            name='voter_token',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['voter_token'], name='calendar_po_voter_t_56f713_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('voter_token', ''), _negated=True)), fields=('slot', 'voter_token'), name='unique_vote_per_guest_token'),
        ),
    ]
