# Generated by Django 6.0.2 on 2026-02-21 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_pollinvitee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status'], name='calendar_po_status_661eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='pollinvitee',
            index=models.Index(fields=['user', 'poll'], name='calendar_po_user_id_039e26_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['slot', 'choice'], name='calendar_po_slot_id_e09ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['slot', 'voter_token'], name='calendar_po_slot_id_c5adc2_idx'),
        ),
    ]
