# Generated by Django 6.0.2 on 2026-02-23 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_add_poll_indexes'),
        ('mail', '0005_mailmessage_has_calendar_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='mail_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_calendars', to='mail.mailaccount'),
        ),
        migrations.AddField(
            model_name='event',
            name='ical_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='ical_uid',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source_message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.mailmessage'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ical_uid'], name='event_ical_uid'),
        ),
    ]
