# Generated by Django 6.0.3 on 2026-03-28 09:58

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0008_calendar_mail_account_event_ical_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendar',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_etag', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sync_interval', models.PositiveIntegerField(default=900, help_text='Sync interval in seconds (default: 15 minutes)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_source', to='calendar.calendar')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'last_synced_at'], name='ext_active_synced')],
            },
        ),
    ]
