# Generated by Django 6.0.4 on 2026-04-13 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0010_rename_organizer_email_external_organizer'),
        ('mail', '0014_mailmessage_mail_acct_read_del_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['calendar', 'is_cancelled', 'start'], name='event_cal_cancel_start'),
        ),
    ]
