# Generated by Django 6.0.4 on 2026-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0011_event_event_cal_cancel_start'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='calendar_ev_calenda_33831b_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='calendar_ev_recurre_4cad78_idx',
        ),
        migrations.RemoveIndex(
            model_name='pollvote',
            name='calendar_po_voter_t_56f713_idx',
        ),
    ]
