# Generated by Django 6.0.7 on 2026-08-01 13:44

from datetime import UTC, datetime

from django.db import migrations, models


def _truncate(dt):
    dt = dt.astimezone(UTC)
    return datetime(dt.year, dt.month, dt.day, tzinfo=UTC)


def normalize_all_day_events(apps, schema_editor):
    """Anchor every all-day start/end at UTC midnight (the day-label invariant)."""
    Event = apps.get_model("calendar", "Event")
    alias = schema_editor.connection.alias
    batch = []
    for event in Event.objects.using(alias).filter(all_day=True).iterator():
        new_start = _truncate(event.start)
        new_end = _truncate(event.end) if event.end else None
        if new_start != event.start or new_end != event.end:
            event.start = new_start
            event.end = new_end
            batch.append(event)
    if batch:
        Event.objects.using(alias).bulk_update(batch, ["start", "end"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0015_event_fulltext_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(normalize_all_day_events, migrations.RunPython.noop),
    ]
