# Generated by Django 6.1 on 2026-08-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0016_event_timezone_and_allday_normalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_rule",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="recurrence_until",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
