# Generated by Django 6.1 on 2026-08-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0018_backfill_recurrence_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrence_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_frequency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_interval',
        ),
    ]
