# Generated by Django 6.1.1 on 2026-09-30 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0019_drop_legacy_recurrence_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmember",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="eventmember",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="eventmember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="eventmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("event", "email"),
                name="unique_event_guest_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("email", ""), ("user__isnull", False)),
                    models.Q(
                        ("user__isnull", True), models.Q(("email", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="event_member_user_xor_email",
            ),
        ),
    ]
