# Generated by Django 6.1.1 on 2026-10-09 19:08

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0020_event_member_external_guest"),
        ("mail", "0035_mailfolder_alias_of"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarObjectChange",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_uuid", models.UUIDField()),
                ("name", models.CharField(max_length=255)),
                ("revision", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="calendar",
            name="feed_token",
            field=models.CharField(
                blank=True, default=None, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="sync_revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="dav_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="ical_extra",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("ics", "ICS invitation"),
                    ("llm", "Extracted by AI"),
                    ("caldav", "Synced from a device"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dav_name", ""), _negated=True),
                fields=("calendar", "dav_name"),
                name="unique_event_dav_name_per_calendar",
            ),
        ),
        migrations.AddField(
            model_name="calendarobjectchange",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_changes",
                to="calendar.calendar",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarobjectchange",
            index=models.Index(
                fields=["calendar", "revision"], name="objchange_cal_rev"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarobjectchange",
            constraint=models.UniqueConstraint(
                fields=("calendar", "event_uuid"),
                name="unique_object_change_per_calendar",
            ),
        ),
    ]
