# Generated by Django 6.1.1 on 2026-09-19 17:17

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('given_name', models.CharField(blank=True, default='', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('addresses', models.JSONField(blank=True, default=list)),
                ('extra_properties', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('has_avatar', models.BooleanField(default=False)),
                ('search_text', models.CharField(blank=True, db_index=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='auth.group')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_persons', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name', 'uuid'],
            },
        ),
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_lists', to='auth.group')),
                ('members', models.ManyToManyField(blank=True, related_name='lists', to='people.person')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'uuid'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner', 'display_name'], name='person_owner_name'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['group', 'display_name'], name='person_group_name'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('owner__isnull', False)), models.Q(('group__isnull', False), ('owner__isnull', True)), _connector='OR'), name='person_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('linked_user__isnull', False), ('owner__isnull', False)), fields=('owner', 'linked_user'), name='person_unique_linked_user_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False), ('linked_user__isnull', False)), fields=('group', 'linked_user'), name='person_unique_linked_user_per_group'),
        ),
        migrations.AddConstraint(
            model_name='personlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('owner__isnull', False)), models.Q(('group__isnull', False), ('owner__isnull', True)), _connector='OR'), name='person_list_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='personlist',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'name'), name='person_list_unique_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='personlist',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('group', 'name'), name='person_list_unique_name_per_group'),
        ),
    ]
