# Generated by Django 6.1.1 on 2026-09-21 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='import_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=16),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner', 'import_uid'], name='person_owner_uid'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['group', 'import_uid'], name='person_group_uid'),
        ),
    ]
