# Generated by Django 6.0.2 on 2026-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='has_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
