# Generated by Django 6.0.2 on 2026-02-09 21:26

import django.db.models.deletion
import workspace.chat.models
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_pinnedconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=workspace.chat.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
