# Generated by Django 6.0.2 on 2026-02-11 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['kind'], name='conv_kind'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['deleted_at'], name='msg_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'created_at'], name='attach_msg_created'),
        ),
    ]
