# Generated by Django 6.0.2 on 2026-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_pinnedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
