# Generated by Django 6.0.2 on 2026-02-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
