# Generated by Django 6.0.2 on 2026-03-01 16:31

import workspace.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=workspace.chat.models.attachment_upload_path),
        ),
    ]
