# Generated by Django 6.0.3 on 2026-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_attachment_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
