# Generated by Django 6.0.3 on 2026-03-29 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_message_tool_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['message', 'emoji'], name='chat_reacti_message_ca5ecd_idx'),
        ),
    ]
