# Generated by Django 6.0.3 on 2026-04-02 18:55

import django.db.models.deletion
from django.db import migrations, models

import workspace.common.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_perf_add_missing_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=2048)),
                ('favicon_url', models.URLField(blank=True, default='', max_length=500)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('fetch_failed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='linkpreview_url')],
            },
        ),
        migrations.CreateModel(
            name='MessageLinkPreview',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_previews', to='chat.message')),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='chat.linkpreview')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['message', 'position'], name='msglp_msg_pos'), models.Index(fields=['created_at'], name='msglp_created_at')],
                'constraints': [models.UniqueConstraint(fields=('message', 'preview'), name='unique_msg_link_preview')],
            },
        ),
    ]
