# Generated by Django 6.0.4 on 2026-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_linkpreview_messagelinkpreview'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_kind',
        ),
        migrations.RemoveIndex(
            model_name='linkpreview',
            name='linkpreview_url',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_d0740f_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagelinkpreview',
            name='msglp_created_at',
        ),
        migrations.AlterField(
            model_name='linkpreview',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
