# Generated by Django 6.0.5 on 2026-05-23 20:06

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_drop_redundant_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInteraction',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('question', 'Question')], max_length=16)),
                ('payload', models.JSONField()),
                ('state', models.JSONField(blank=True, null=True)),
                ('interacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_interactions', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='chat.message')),
            ],
            options={
                'indexes': [models.Index(fields=['interacted_at'], name='chat_messag_interac_cee4e4_idx')],
            },
        ),
    ]
