# Generated by Django 6.0.5 on 2026-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_messageinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='type',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
        ),
    ]
