# Generated by Django 6.0.5 on 2026-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_add_attachment_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='category',
            field=models.CharField(db_index=True, default='unknown', max_length=20),
        ),
    ]
