# Generated by Django 6.0.6 on 2026-06-20 09:20

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_reaction_user_created_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=8),
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=8)),
                ('media_kind', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('screen', 'Screen')], default='audio', max_length=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='chat.conversation')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('system_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_session', to='chat.message')),
            ],
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.callsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['conversation', 'state'], name='chat_callse_convers_b520c6_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['state'], name='chat_callse_state_7a15a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='callsession',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('conversation',), name='one_active_call_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['session', 'left_at'], name='chat_callpa_session_c5d2a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='callparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_call_participant'),
        ),
    ]
