# Generated by Django 6.0.7 on 2026-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0021_chat_fulltext_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='auth.group'),
        ),
    ]
