# Generated by Django 6.0.7 on 2026-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_strip_tool_badges_from_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='ai_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
