# Generated by Django 6.0.7 on 2026-08-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_messageattachment_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='viewer',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
