# Generated by Django 6.0.7 on 2026-08-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_messageattachment_viewer_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmember",
            name="notification_level",
            field=models.CharField(
                choices=[
                    ("all", "All messages"),
                    ("mentions", "Mentions only"),
                    ("none", "Nothing"),
                ],
                default="all",
                max_length=8,
            ),
        ),
    ]
