# Generated by Django 6.0.7 on 2026-08-12 13:55

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0026_conversationmember_notification_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadParticipant",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="last_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="thread_root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="thread_replies",
                to="chat.message",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "thread_root", "created_at"],
                name="msg_conv_thread_created",
            ),
        ),
        migrations.AddField(
            model_name="threadparticipant",
            name="root_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="threadparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_thread_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="threadparticipant",
            index=models.Index(
                fields=["user", "root_message"], name="chat_thread_user_id_845750_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="threadparticipant",
            constraint=models.UniqueConstraint(
                fields=("root_message", "user"), name="unique_thread_participant"
            ),
        ),
    ]
