# Generated by Django 6.1 on 2026-08-31 08:32

import django.db.models.deletion
import workspace.chat.models
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0016_event_timezone_and_allday_normalization"),
        ("chat", "0030_name_untitled_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default=workspace.chat.models._generate_meeting_slug,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "closed_occurrence_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting",
                        to="chat.conversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting",
                        to="calendar.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingGuest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=80)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("admitted", "Admitted"),
                            ("refused", "Refused"),
                            ("removed", "Removed"),
                        ],
                        default="waiting",
                        max_length=8,
                    ),
                ),
                ("occurrence_start", models.DateTimeField()),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("admitted_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="chat.meeting",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["meeting", "state"],
                        name="chat_meetin_meeting_cb8d1f_idx",
                    ),
                    models.Index(
                        fields=["meeting", "occurrence_start"],
                        name="chat_meetin_meeting_e4feb0_idx",
                    ),
                ],
            },
        ),
    ]
