# Generated by Django 6.1 on 2026-08-31 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0031_meeting_meetingguest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="callparticipant",
            name="unique_call_participant",
        ),
        migrations.AddField(
            model_name="callparticipant",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chat.meetingguest",
            ),
        ),
        migrations.AddField(
            model_name="callsession",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chat.meetingguest",
            ),
        ),
        migrations.AlterField(
            model_name="callparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="callparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="call_participant_one_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="callparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="unique_call_participant_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="callparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False)),
                fields=("session", "guest"),
                name="unique_call_participant_guest",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("author__isnull", False), ("guest__isnull", True)),
                    models.Q(("author__isnull", True), ("guest__isnull", False)),
                    _connector="OR",
                ),
                name="message_one_identity",
            ),
        ),
    ]
