# Generated by Django 6.1 on 2026-09-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0032_remove_callparticipant_unique_call_participant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
