# Generated by Django 6.1 on 2026-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0033_meeting_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="locked",
        ),
        migrations.AddField(
            model_name="meeting",
            name="locked_occurrence_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
