# Generated by Django 6.1 on 2026-09-07 18:58

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


def backfill_titles(apps, schema_editor):
    Meeting = apps.get_model("chat", "Meeting")
    db = schema_editor.connection.alias
    for meeting in (
        Meeting.objects.using(db).select_related("event").filter(title="").iterator()
    ):
        if meeting.event_id is not None:
            meeting.title = meeting.event.title[:200]
            meeting.save(update_fields=["title"])


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0019_drop_legacy_recurrence_columns"),
        ("chat", "0034_meeting_locked_occurrence_start"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurrence_start", models.DateTimeField(blank=True, null=True)),
                ("body", models.TextField()),
                ("body_html", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="callsession",
            name="one_active_call_per_conversation",
        ),
        migrations.AddField(
            model_name="callsession",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sessions",
                to="chat.meeting",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="public_link_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_titles, migrations.RunPython.noop),
        migrations.AddField(
            model_name="meetingguest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="callsession",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sessions",
                to="chat.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting",
                to="chat.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="event",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting",
                to="calendar.event",
            ),
        ),
        migrations.AddIndex(
            model_name="callsession",
            index=models.Index(
                fields=["meeting", "state"], name="chat_callse_meeting_992577_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="callsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("conversation__isnull", False), ("meeting__isnull", True)
                    ),
                    models.Q(
                        ("conversation__isnull", True), ("meeting__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="call_session_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="callsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("conversation__isnull", False), ("state", "active")
                ),
                fields=("conversation",),
                name="one_active_call_per_conversation",
            ),
        ),
        migrations.AddConstraint(
            model_name="callsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("meeting__isnull", False), ("state", "active")),
                fields=("meeting",),
                name="one_active_call_per_meeting",
            ),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.meetingguest",
            ),
        ),
        migrations.AddField(
            model_name="meetingmessage",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.meeting",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingmessage",
            index=models.Index(
                fields=["meeting", "created_at"], name="mmsg_meeting_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("author__isnull", False), ("guest__isnull", True)),
                    models.Q(("author__isnull", True), ("guest__isnull", False)),
                    _connector="OR",
                ),
                name="meeting_message_one_identity",
            ),
        ),
    ]
