# Generated by Django 6.1 on 2026-09-08 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_guest_authored_rows(apps, schema_editor):
    """Guest-authored rows only ever existed on the unmerged branch that
    introduced them; nothing points at a Message a guest wrote."""
    Message = apps.get_model("chat", "Message")
    db = schema_editor.connection.alias
    Message.objects.using(db).filter(author__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0035_meeting_scope_and_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="message_one_identity",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="conversation",
        ),
        migrations.RunPython(drop_guest_authored_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="guest",
        ),
    ]
