from django.db import transaction
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import extend_schema_field
from rest_framework import serializers

from workspace.files.services import FileService
from .models import File, FileComment


def _require_annotation(obj, name):
    """Fetch an annotation from *obj* or raise a loud error.

    ``FileSerializer`` deliberately has no DB fallback when an annotation is
    missing — callers must pipe their queryset through
    ``FileService.annotate_for_serializer`` before handing it to the serializer.
    This helper turns a missing annotation into a clear exception instead of a
    silent N+1.
    """
    try:
        return getattr(obj, name)
    except AttributeError as exc:
        raise AttributeError(
            f"FileSerializer requires the {name!r} annotation. "
            f"Use FileService.annotate_for_serializer(qs, user) on the queryset."
        ) from exc


class FileSerializer(serializers.ModelSerializer):
    is_folder = serializers.SerializerMethodField(
        help_text="True when node_type is 'folder'."
    )
    is_file = serializers.SerializerMethodField(
        help_text="True when node_type is 'file'."
    )
    is_favorite = serializers.SerializerMethodField(
        help_text="True when the current user has favorited this item."
    )
    category = serializers.SerializerMethodField(
        help_text="File category (text, image, pdf, video, audio, unknown)."
    )
    is_viewable = serializers.SerializerMethodField(
        help_text="True if file can be viewed in browser."
    )
    content_url = serializers.SerializerMethodField(
        help_text="URL to fetch file content for viewing."
    )
    is_pinned = serializers.SerializerMethodField(
        help_text="True when the current user has pinned this folder to the sidebar."
    )
    is_shared = serializers.SerializerMethodField(
        help_text="True when the file has been shared with at least one user."
    )
    tags = serializers.SerializerMethodField(
        help_text="Tags assigned to this file."
    )
    has_children = serializers.SerializerMethodField(
        help_text="True when a folder contains child folders (folders only)."
    )

    class Meta:
        model = File
        fields = [
            'uuid',
            'name',
            'node_type',
            'parent',
            'content',
            'size',
            'mime_type',
            'icon',
            'color',
            'owner',
            'group',
            'created_at',
            'updated_at',
            'deleted_at',
            'path',
            'is_folder',
            'is_file',
            'is_favorite',
            'category',
            'is_viewable',
            'content_url',
            'is_pinned',
            'is_shared',
            'tags',
            'has_children',
        ]
        read_only_fields = ['owner', 'created_at', 'updated_at', 'deleted_at', 'size', 'path', 'is_favorite', 'is_pinned', 'is_shared', 'tags']
        extra_kwargs = {
            'uuid': {
                'help_text': 'Unique identifier. Generated by the server if omitted.'
            },
            'name': {'help_text': 'Display name of the file or folder.'},
            'node_type': {'help_text': "Either 'file' or 'folder'."},
            'parent': {'help_text': 'Parent folder UUID.'},
            'content': {
                'help_text': 'File payload. Must be empty for folders.',
                'allow_empty_file': True,
                'required': False,
                'write_only': True,
            },
            'size': {'help_text': 'File size in bytes.'},
            'mime_type': {'help_text': 'MIME type for file nodes.'},
            'owner': {'help_text': 'Owner user id.'},
            'created_at': {'help_text': 'Creation timestamp.'},
            'updated_at': {'help_text': 'Last update timestamp.'},
        }

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_is_folder(self, obj):
        return obj.is_folder()

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_is_file(self, obj):
        return obj.is_file()

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_is_favorite(self, obj):
        return bool(_require_annotation(obj, 'is_favorite'))

    @extend_schema_field(OpenApiTypes.STR)
    def get_category(self, obj):
        from .utils import FileTypeDetector

        if obj.node_type != File.NodeType.FILE:
            return None
        return FileTypeDetector.categorize(obj.mime_type or '').value

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_is_viewable(self, obj):
        from .utils import FileTypeDetector

        if obj.node_type != File.NodeType.FILE:
            return False
        return FileTypeDetector.is_viewable(obj.mime_type or '')

    @extend_schema_field(OpenApiTypes.STR)
    def get_content_url(self, obj):
        if obj.node_type == File.NodeType.FILE and obj.content:
            return f'/api/v1/files/{obj.uuid}/content'
        return None

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_is_pinned(self, obj):
        if obj.node_type != File.NodeType.FOLDER:
            return False
        return bool(_require_annotation(obj, 'is_pinned'))

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_is_shared(self, obj):
        return bool(_require_annotation(obj, 'is_shared'))

    @extend_schema_field(OpenApiTypes.BOOL)
    def get_has_children(self, obj):
        if obj.node_type != File.NodeType.FOLDER:
            return False
        return bool(_require_annotation(obj, 'has_children'))

    @extend_schema_field({'type': 'array', 'items': {'type': 'object'}})
    def get_tags(self, obj):
        fts = obj.file_tags.all()  # uses prefetch cache if available
        return [{'uuid': str(ft.tag.uuid), 'name': ft.tag.name, 'icon': ft.tag.icon, 'color': ft.tag.color} for ft in fts]

    def validate_name(self, value):
        if '/' in value:
            raise serializers.ValidationError("File and folder names must not contain '/'.")
        return value

    def validate(self, attrs):
        if self.instance is not None:
            errors = {}
            initial_data = self.initial_data or {}

            if 'uuid' in initial_data:
                incoming_uuid = str(initial_data.get('uuid')).lower()
                if incoming_uuid != str(self.instance.uuid).lower():
                    errors['uuid'] = 'This field is immutable.'

            if 'owner' in initial_data:
                incoming_owner = str(initial_data.get('owner'))
                if incoming_owner != str(self.instance.owner_id):
                    errors['owner'] = 'This field is immutable.'

            if 'node_type' in initial_data:
                if str(initial_data.get('node_type')) != self.instance.node_type:
                    errors['node_type'] = 'This field is immutable.'

            if 'group' in initial_data:
                errors['group'] = 'Group cannot be changed directly.'

            if errors:
                raise serializers.ValidationError(errors)

        node_type = attrs.get('node_type')
        instance = self.instance
        if instance is not None and node_type is None:
            node_type = instance.node_type

        # Validate parent assignment via FileService
        if 'parent' in attrs and instance is not None:
            try:
                FileService.validate_move_target(instance, attrs['parent'], user=self.context['request'].user)
            except ValueError as e:
                raise serializers.ValidationError({'parent': e.args[0]})

        # Validate file name uniqueness via FileService
        if node_type == File.NodeType.FILE:
            name = attrs.get('name') or (instance.name if instance else None)
            parent = attrs.get('parent') if 'parent' in attrs else (instance.parent if instance else None)
            owner = instance.owner if instance else self.context['request'].user
            if name:
                try:
                    FileService.check_name_available(
                        owner, parent, name, node_type,
                        exclude_pk=instance.pk if instance else None,
                    )
                except ValueError as e:
                    raise serializers.ValidationError({'name': e.args[0]})

        return super().validate(attrs)

    def create(self, validated_data):
        owner = self.context['request'].user
        node_type = validated_data.get('node_type')
        group = validated_data.get('group')

        if node_type == File.NodeType.FOLDER:
            instance = FileService.create_folder(
                owner=owner,
                name=validated_data['name'],
                parent=validated_data.get('parent'),
                icon=validated_data.get('icon'),
                color=validated_data.get('color'),
                group=group,
            )
        else:
            instance = FileService.create_file(
                owner=owner,
                name=validated_data['name'],
                parent=validated_data.get('parent'),
                content=validated_data.get('content'),
                mime_type=validated_data.get('mime_type'),
                group=group,
            )

        # A freshly-created node cannot have favorites, pins, shares, or
        # children yet — attach the annotations the serializer now requires
        # so the DRF `create()` response can be built without a re-fetch.
        instance.is_favorite = False
        instance.is_pinned = False
        instance.is_shared = False
        instance.has_children = False
        return instance

    @transaction.atomic
    def update(self, instance, validated_data):
        # Pop content + caller-supplied mime_type so they go through FileService
        # rather than the default ModelSerializer assignment loop.
        content_provided = 'content' in validated_data
        uploaded = validated_data.pop('content', None)
        explicit_mime_type = validated_data.pop('mime_type', None)

        # Handle rename via FileService (storage moves)
        if 'name' in validated_data:
            new_name = validated_data['name']
            if instance.name != new_name:
                FileService.rename(instance, new_name)

        # Handle move via FileService (storage moves)
        if 'parent' in validated_data:
            new_parent = validated_data['parent']
            old_parent_id = instance.parent_id
            new_parent_id = new_parent.pk if new_parent else None
            if old_parent_id != new_parent_id:
                FileService.move(instance, new_parent, acting_user=self.context['request'].user)

        instance = super().update(instance, validated_data)

        if content_provided:
            if instance.node_type == File.NodeType.FILE and uploaded is not None:
                FileService.update_content(
                    instance, uploaded,
                    name=instance.name,
                    mime_type=explicit_mime_type,
                )
            else:
                instance.content = uploaded
                instance.size = None
                instance.save(update_fields=['content', 'size'])
        elif explicit_mime_type is not None:
            instance.mime_type = explicit_mime_type
            instance.save(update_fields=['mime_type'])

        return instance


class FileCommentAuthorSerializer(serializers.Serializer):
    id = serializers.IntegerField(source='pk')
    username = serializers.CharField()
    first_name = serializers.CharField()
    last_name = serializers.CharField()
    avatar_url = serializers.SerializerMethodField()

    @extend_schema_field(OpenApiTypes.STR)
    def get_avatar_url(self, obj):
        return f'/api/v1/users/{obj.pk}/avatar'


class FileCommentSerializer(serializers.ModelSerializer):
    author = FileCommentAuthorSerializer(read_only=True)

    class Meta:
        model = FileComment
        fields = ['uuid', 'file', 'author', 'body', 'edited_at', 'created_at', 'deleted_at']
        read_only_fields = ['uuid', 'file', 'author', 'edited_at', 'created_at', 'deleted_at']


class FileCommentCreateSerializer(serializers.Serializer):
    body = serializers.CharField()


class FileCommentEditSerializer(serializers.Serializer):
    body = serializers.CharField()
