# Generated by Django 6.0 on 2026-01-23 20:19

import django.db.models.deletion
import workspace.common.uuids
import workspace.files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('content', models.FileField(blank=True, null=True, upload_to=workspace.files.models.file_upload_path)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.file')),
            ],
            options={
                'ordering': ['node_type', 'name'],
                'indexes': [models.Index(fields=['parent', 'node_type'], name='files_file_parent__10af33_idx'), models.Index(fields=['owner', 'created_at'], name='files_file_owner_i_a41654_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('node_type', 'folder'), models.Q(('content__isnull', True), ('content', ''), _connector='OR')), ('node_type', 'file'), _connector='OR'), name='folder_has_no_content')],
            },
        ),
    ]
