# Generated by Django 6.0 on 2026-01-24 18:39

import workspace.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=workspace.files.models.file_upload_path),
        ),
    ]
