# Generated by Django 6.0 on 2026-01-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_filefavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'deleted_at'], name='file_owner_del_idx'),
        ),
    ]
