# Generated by Django 6.0 on 2026-01-25 20:41

from django.db import migrations, models

import workspace.files.models
import workspace.files.storage


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=workspace.files.storage.OverwriteStorage(), upload_to=workspace.files.models.file_upload_path),
        ),
    ]
