# Generated by Django 6.0 on 2026-01-27 18:56

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedFolder',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(limit_choices_to={'node_type': 'folder'}, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='files.file')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['owner', 'position'], name='pinned_owner_pos')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'folder'), name='unique_pinned_folder')],
            },
        ),
    ]
