# Generated by Django 6.0 on 2026-01-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_pinnedfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='color',
            field=models.CharField(blank=True, help_text="Custom color class for folder icon (e.g., 'text-error', 'text-success')", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='icon',
            field=models.CharField(blank=True, help_text="Custom Lucide icon name for folders (e.g., 'briefcase', 'heart')", max_length=50, null=True),
        ),
    ]
