# Generated by Django 6.0 on 2026-02-01 10:17

import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_add_folder_icon_customization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MimeTypeRule',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pattern', models.CharField(help_text="MIME type or wildcard (e.g. 'text/*')", max_length=100, unique=True)),
                ('is_wildcard', models.BooleanField(default=False, editable=False)),
                ('priority', models.IntegerField(default=100, help_text='Lower = matched first')),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(help_text='DaisyUI/Tailwind color class', max_length=50)),
                ('category', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('viewer_type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('markdown', 'Markdown'), ('pdf', 'PDF'), ('media', 'Media')], max_length=10, null=True)),
            ],
            options={
                'ordering': ['priority', 'pattern'],
            },
        ),
    ]
