# Generated by Django 6.0.1 on 2026-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_fileshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='permission',
            field=models.CharField(choices=[('ro', 'Read only'), ('rw', 'Read & write')], default='ro', max_length=2),
        ),
    ]
