# Generated by Django 6.0.2 on 2026-02-11 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_filecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filecomment',
            index=models.Index(fields=['deleted_at'], name='file_comment_deleted_at'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['shared_by', 'created_at'], name='file_share_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='mimetyperule',
            index=models.Index(fields=['priority', 'pattern'], name='mime_priority_pattern'),
        ),
    ]
