# Generated by Django 6.0.3 on 2026-03-21 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import workspace.common.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_share_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='ghost', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='files.file')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='files.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_tag_per_user'),
        ),
        migrations.AddConstraint(
            model_name='filetag',
            constraint=models.UniqueConstraint(fields=('file', 'tag'), name='unique_file_tag'),
        ),
    ]
