# Generated by Django 6.0.3 on 2026-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_tag_filetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
