# Generated by Django 6.0.3 on 2026-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_add_mime_type_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
