# Generated by Django 6.0.3 on 2026-03-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0020_add_tag_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_files', to='auth.group'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['group', 'deleted_at'], name='file_group_del_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('group__isnull', False), ('parent__isnull', True)), fields=('group',), name='unique_group_root_folder'),
        ),
    ]
