# Generated by Django 6.0.3 on 2026-03-25 19:57

from django.db import migrations


def migrate_storage_paths(apps, schema_editor):
    """Update content.name for all existing files: files/<user>/ -> files/users/<user>/."""
    File = apps.get_model('files', 'File')
    files = File.objects.filter(
        node_type='file',
    ).exclude(content='').exclude(content__isnull=True)

    updated = []
    for f in files.iterator(chunk_size=500):
        if not f.content.name:
            continue
        name = f.content.name.replace('\\', '/')
        if name.startswith('files/') and not name.startswith('files/users/') and not name.startswith('files/groups/'):
            f.content.name = 'files/users/' + name[len('files/'):]
            updated.append(f)
        if len(updated) >= 500:
            File.objects.bulk_update(updated, ['content'], batch_size=500)
            updated = []
    if updated:
        File.objects.bulk_update(updated, ['content'], batch_size=500)


def move_physical_files(apps, schema_editor):
    """Move physical directories on disk from files/<user>/ to files/users/<user>/."""
    import os
    from django.core.files.storage import default_storage

    try:
        files_root = default_storage.path('files')
    except NotImplementedError:
        return

    if not os.path.isdir(files_root):
        return

    users_dir = os.path.join(files_root, 'users')
    os.makedirs(users_dir, exist_ok=True)

    for entry in os.listdir(files_root):
        entry_path = os.path.join(files_root, entry)
        if entry in ('users', 'groups') or not os.path.isdir(entry_path):
            continue
        dest = os.path.join(users_dir, entry)
        if not os.path.exists(dest):
            os.rename(entry_path, dest)


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_file_group_file_file_group_del_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(move_physical_files, migrations.RunPython.noop),
        migrations.RunPython(migrate_storage_paths, migrations.RunPython.noop),
    ]
