# Generated by Django 6.0.3 on 2026-03-29 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_migrate_storage_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filetag',
            index=models.Index(fields=['file', 'tag'], name='files_filet_file_id_b06e75_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner', 'name'], name='files_tag_owner_i_2d33dd_idx'),
        ),
    ]
