# Generated by Django 6.0.4 on 2026-04-13 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0023_perf_add_missing_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'deleted_at', 'node_type'], name='file_owner_del_type'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['parent', 'deleted_at', 'name'], name='file_parent_del_name'),
        ),
    ]
