# Generated by Django 6.0.4 on 2026-04-28 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0024_file_file_owner_del_type_file_file_parent_del_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['path'], name='file_path_idx', opclasses=['text_pattern_ops']),
        ),
    ]
