# Generated by Django 6.0.4 on 2026-04-28 17:57

import workspace.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_add_file_path_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesharelink',
            name='token',
            field=models.CharField(default=workspace.files.models._generate_share_link_token, max_length=44, unique=True),
        ),
    ]
