# Generated by Django 6.0.4 on 2026-05-09 08:57

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_drop_redundant_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEvent',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('content_replaced', 'Content replaced'), ('deleted', 'Moved to trash'), ('restored', 'Restored from trash'), ('shared', 'Shared'), ('share_permission_changed', 'Share permission changed'), ('unshared', 'Unshared'), ('link_created', 'Public link created'), ('link_revoked', 'Public link revoked')], db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_events', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='files.file')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file', '-created_at'], name='file_event_file_created')],
            },
        ),
    ]
