# Generated by Django 6.0.4 on 2026-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0027_add_file_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('content_replaced', 'Updated'), ('deleted', 'Trashed'), ('restored', 'Restored'), ('shared', 'Shared'), ('share_permission_changed', 'Permission changed'), ('unshared', 'Unshared'), ('link_created', 'Link created'), ('link_revoked', 'Link revoked')], db_index=True, max_length=32),
        ),
    ]
