# Generated by Django 6.0.5 on 2026-05-25 08:29

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0029_fix_group_storage_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['node_type', django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
