# Generated by Django 6.0.5 on 2026-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0030_case_insensitive_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
