# Generated by Django 6.0.5 on 2026-05-27 19:22

from django.db import migrations, models


def backfill_null_types(apps, schema_editor):
    File = apps.get_model('files', 'File')
    File.objects.filter(type__isnull=True).update(type='unknown')


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0031_add_type_field'),
    ]

    operations = [
        migrations.RunPython(backfill_null_types, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='mimetyperule',
            name='mime_priority_pattern',
        ),
        migrations.DeleteModel(
            name='MimeTypeRule',
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
        ),
    ]
