# Generated by Django 6.0.5 on 2026-05-28 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0033_add_category_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='file_owner_del_type',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'deleted_at', 'node_type'], include=('size',), name='file_owner_del_type_size'),
        ),
    ]
