# Generated by Django 6.0.6 on 2026-06-13 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0035_relabel_misdetected_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('has_thumbnail', False), ('node_type', 'file')), fields=['type'], name='file_thumb_pending_idx'),
        ),
    ]
