# Generated by Django 6.0.6 on 2026-06-13 18:33

import django.db.models.deletion
from django.db import migrations, models

import workspace.common.uuids


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0036_file_file_thumb_pending_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileLink",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="files.file",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["target"], name="file_link_target_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target"), name="unique_file_link"
                    )
                ],
            },
        ),
    ]
