# Generated by Django 6.0.6 on 2026-07-06 20:50

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("files", "0037_filelink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                models.F("owner"),
                models.F("deleted_at"),
                models.OrderBy(models.F("updated_at"), descending=True),
                django.db.models.functions.text.Lower("name"),
                name="file_owner_del_recent",
            ),
        ),
    ]
