# Generated by Django 6.0.7 on 2026-07-26 07:44

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0038_file_file_owner_del_recent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailFailure",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField()),
                ("last_error", models.CharField(blank=True, max_length=200)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail_failure",
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
