# Generated by Django 6.0.7 on 2026-08-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0039_thumbnailfailure'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='viewer',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
