# Generated by Django 6.0.7 on 2026-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0041_tag_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
