# Generated by Django 6.1 on 2026-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0042_file_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='wopi_lock',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
