# Generated by Django 6.1 on 2026-08-25 11:52

import django.core.validators
import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0043_file_lock_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStorageQuota',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quota_bytes', models.BigIntegerField(blank=True, help_text="Bytes allowed in this group's folder. Leave empty for unlimited.", null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Why this group deviates from the default.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quota_bytes', models.BigIntegerField(blank=True, help_text='Bytes allowed for personal files. Leave empty for unlimited.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Why this user deviates from the default.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
