# Generated by Django 6.1 on 2026-08-25 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0045_groupstoragequota_userstoragequota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('group__isnull', True)), fields=['owner', 'node_type'], include=('size',), name='file_personal_usage'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['group', 'node_type'], include=('size',), name='file_group_usage'),
        ),
    ]
