# Generated by Django 6.1 on 2026-08-25 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("files", "0045_file_file_personal_usage_file_file_group_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="file",
            name="file_group_usage",
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                condition=models.Q(("group__isnull", False)),
                fields=["group", "node_type"],
                include=("size",),
                name="file_group_usage",
            ),
        ),
    ]
