# Generated by Django 6.1 on 2026-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0048_files_fulltext_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fts_rowid',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
