# Generated by Django 6.1 on 2026-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0049_file_fts_rowid"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesharelink",
            name="max_file_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filesharelink",
            name="max_file_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filesharelink",
            name="mode",
            field=models.CharField(
                choices=[
                    ("read", "Read only"),
                    ("drop", "Upload only"),
                    ("both", "Read and upload"),
                ],
                default="read",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="filesharelink",
            name="notified_upload_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="filesharelink",
            name="upload_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fileevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("renamed", "Renamed"),
                    ("moved", "Moved"),
                    ("content_replaced", "Updated"),
                    ("deleted", "Trashed"),
                    ("restored", "Restored"),
                    ("shared", "Shared"),
                    ("share_permission_changed", "Permission changed"),
                    ("unshared", "Unshared"),
                    ("link_created", "Link created"),
                    ("link_revoked", "Link revoked"),
                    ("link_upload", "Uploaded via link"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
