# Generated by Django 6.1 on 2026-08-30 22:12

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0049_file_fts_rowid"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileScan",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("skipped", "Skipped"),
                            ("error", "Scan failed"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("signature", models.CharField(blank=True, default="", max_length=200)),
                ("detail", models.CharField(blank=True, default="", max_length=500)),
                ("scanned_at", models.DateTimeField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "-scanned_at"], name="file_scan_status_time"
                    )
                ],
            },
        ),
    ]
