# Generated by Django 6.1 on 2026-08-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0050_filescan'),
    ]

    operations = [
        migrations.AddField(
            model_name='filescan',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
