# Generated by Django 6.1.1 on 2026-09-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0054_tag_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileshare',
            name='unique_file_share',
        ),
        migrations.AddField(
            model_name='fileshare',
            name='shared_with_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_file_shares', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['shared_with_group', 'created_at'], name='file_share_recv_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shared_with__isnull', False), ('shared_with_group__isnull', True)), models.Q(('shared_with__isnull', True), ('shared_with_group__isnull', False)), _connector='OR'), name='file_share_one_target'),
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_with__isnull', False)), fields=('file', 'shared_with'), name='unique_file_share_user'),
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_with_group__isnull', False)), fields=('file', 'shared_with_group'), name='unique_file_share_group'),
        ),
    ]
