# Generated by Django 6.1.1 on 2026-09-25 17:02

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0056_fileshare_project_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaInfo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "video_codec",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "audio_codec",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("probed_at", models.DateTimeField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_info",
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
