# Generated by Django 6.1.1 on 2026-09-25 19:10

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0058_search_index_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileLinkState",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("extractor_version", models.PositiveSmallIntegerField()),
                ("reconciled_at", models.DateTimeField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_state",
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
