# Generated by Django 6.1.1 on 2026-10-03 16:12

from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_last_event_at(apps, schema_editor):
    File = apps.get_model("files", "File")
    FileEvent = apps.get_model("files", "FileEvent")
    db = schema_editor.connection.alias
    events = FileEvent.objects.using(db).filter(file=OuterRef("pk"))
    newest = events.order_by("-created_at").values("created_at")[:1]
    # A null actor is a system event, foreign to the owner like anyone else.
    newest_foreign = (
        events.exclude(actor_id=OuterRef("owner_id"))
        .order_by("-created_at")
        .values("created_at")[:1]
    )
    File.objects.using(db).update(
        last_event_at=Subquery(newest), last_foreign_event_at=Subquery(newest_foreign)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0060_retype_isobmff_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_event_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_foreign_event_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_last_event_at, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('node_type', 'file'), models.Q(('mime_type', 'text/markdown'), _negated=True), ('last_event_at__isnull', False)), fields=['owner', '-last_event_at'], name='file_owner_recent_file'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('mime_type', 'text/markdown'), ('node_type', 'file'), ('last_event_at__isnull', False)), fields=['owner', '-last_event_at'], name='file_owner_recent_note'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('node_type', 'file'), models.Q(('mime_type', 'text/markdown'), _negated=True), ('last_foreign_event_at__isnull', False)), fields=['owner', '-last_foreign_event_at'], name='file_owner_foreign_file'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('mime_type', 'text/markdown'), ('node_type', 'file'), ('last_foreign_event_at__isnull', False)), fields=['owner', '-last_foreign_event_at'], name='file_owner_foreign_note'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('node_type', 'file'), models.Q(('mime_type', 'text/markdown'), _negated=True), ('group__isnull', False), ('last_event_at__isnull', False)), fields=['group', '-last_event_at'], name='file_group_recent_file'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('mime_type', 'text/markdown'), ('node_type', 'file'), ('group__isnull', False), ('last_event_at__isnull', False)), fields=['group', '-last_event_at'], name='file_group_recent_note'),
        ),
    ]
