# Generated by Django 6.1.1 on 2026-10-03 20:39

import workspace.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0061_file_last_event_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                storage=workspace.files.models.files_storage,
                upload_to=workspace.files.models.file_upload_path,
            ),
        ),
    ]
