# Generated by Django 6.0.4 on 2026-04-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordfolder',
            name='folder_vault_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordfolder',
            name='folder_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordtag',
            name='tag_vault_idx',
        ),
        migrations.RemoveIndex(
            model_name='vault',
            name='vault_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaultgroupaccess',
            name='vault_group_vault_idx',
        ),
    ]
