# Generated by Django 6.0.4 on 2026-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_userkepair_vaultmember_vaultgroupaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='vault',
            name='color',
            field=models.CharField(blank=True, default='text-warning', max_length=50),
        ),
    ]
