# Generated by Django 6.0.7 on 2026-07-21 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_taskevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskevent",
            options={"ordering": ["-created_at", "-uuid"]},
        ),
    ]
