# Generated by Django 6.0.7 on 2026-07-21 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_taskevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['actor', '-created_at'], name='taskevent_actor_recent'),
        ),
    ]
