# Generated by Django 6.0.7 on 2026-07-28 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_backfill_task_references"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="key",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="number",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="unique_task_number_per_project"
            ),
        ),
    ]
