# Generated by Django 6.0.7 on 2026-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_require_task_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="done_retention_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
