# Generated by Django 6.0.7 on 2026-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_rekey_personal_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("moved", "Moved"),
                    ("completed", "Completed"),
                    ("deleted", "Deleted"),
                    ("commented", "Commented"),
                ],
                max_length=9,
            ),
        ),
    ]
