# Generated by Django 6.1 on 2026-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_taskevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimate_unit',
            field=models.CharField(blank=True, choices=[('points', 'Story points'), ('hours', 'Hours')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='from_value',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='to_value',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('estimate', 'Estimated')], max_length=9),
        ),
    ]
