# Generated by Django 6.1 on 2026-08-21 13:18

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_estimate_unit_task_estimate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('estimate', 'Estimated')], max_length=9),
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue')], max_length=7)),
                ('due_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'user', 'kind'), name='taskreminder_once_per_kind')],
            },
        ),
    ]
