# Generated by Django 6.1 on 2026-08-21 13:48

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_taskevent_type_taskreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
