# Generated by Django 6.1 on 2026-08-21 19:18

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_taskevent_type_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('estimate', 'Estimated'), ('attached', 'Attached'), ('detached', 'Detached'), ('linked', 'Linked'), ('unlinked', 'Unlinked')], max_length=9),
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('blocks', 'Blocks'), ('duplicates', 'Duplicates'), ('relates_to', 'Relates to')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='projects.task')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='projects.task')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'type'), name='unique_task_link'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='task_link_not_self')],
            },
        ),
    ]
