# Generated by Django 6.1 on 2026-08-23 08:49

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_taskattachment_owned_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='from_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='to_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('estimate', 'Estimated'), ('epic', 'Epic'), ('attached', 'Attached'), ('detached', 'Detached'), ('linked', 'Linked'), ('unlinked', 'Unlinked')], max_length=9),
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.epic'),
        ),
        migrations.AddConstraint(
            model_name='epic',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_epic_name_per_project'),
        ),
    ]
