# Generated by Django 6.1 on 2026-09-02 07:15

from django.db import migrations, models
from django.db.models import CharField, Exists, OuterRef, Subquery, Value
from django.db.models.functions import Cast, Coalesce


def backfill_categories(apps, schema_editor):
    """Resolve the snapshotted status names against each project's current
    columns, one correlated UPDATE per side. Best effort: an event naming a
    column that has since been renamed or deleted stays blank, and
    COMPLETED events land on "done" regardless - that is what the type
    means."""
    TaskStatus = apps.get_model("projects", "TaskStatus")
    TaskEvent = apps.get_model("projects", "TaskEvent")
    db = schema_editor.connection.alias
    events = TaskEvent.objects.using(db)
    for side in ("from", "to"):
        category = (
            TaskStatus.objects.using(db)
            .filter(project_id=OuterRef("project_id"), name=OuterRef(f"{side}_status"))
            .values("category")[:1]
        )
        events.exclude(**{f"{side}_status": ""}).update(
            **{f"{side}_category": Coalesce(Subquery(category), Value(""))}
        )
    events.filter(type="completed").exclude(to_status="").update(to_category="done")


def backfill_sprint_refs(apps, schema_editor):
    """Point SPRINT events at the sprint their name snapshot designates.

    A sprint deleted since cannot be resolved and stays null; a name reused
    after such a deletion resolves to the surviving sprint only for events
    written after it was created, so the former sprint's trail is not
    claimed by the new one."""
    Sprint = apps.get_model("projects", "Sprint")
    TaskEvent = apps.get_model("projects", "TaskEvent")
    db = schema_editor.connection.alias
    events = TaskEvent.objects.using(db).filter(type="sprint")
    for side in ("from", "to"):
        sprint = (
            Sprint.objects.using(db)
            .filter(
                project_id=OuterRef("project_id"),
                name=OuterRef(f"{side}_value"),
                created_at__lte=OuterRef("created_at"),
            )
            .values("uuid")[:1]
        )
        events.exclude(**{f"{side}_value": ""}).update(
            **{f"{side}_ref": Subquery(sprint)}
        )


def backfill_creation_estimates(apps, schema_editor):
    """Write the estimate each task was born with on its CREATED event.

    The first ESTIMATED event of a task says what the estimate was before
    the first change; a task never re-estimated still carries it today. A
    task deleted without ever being re-estimated is unrecoverable and its
    CREATED event stays blank."""
    Task = apps.get_model("projects", "Task")
    TaskEvent = apps.get_model("projects", "TaskEvent")
    db = schema_editor.connection.alias
    events = TaskEvent.objects.using(db)
    created = events.filter(type="created")
    first_change = events.filter(
        project_id=OuterRef("project_id"),
        task_number=OuterRef("task_number"),
        type="estimate",
    ).order_by("created_at", "uuid")
    current = Task.objects.using(db).filter(
        pk=OuterRef("task_id"), estimate__isnull=False
    )
    created.filter(Exists(current)).update(
        to_value=Cast(
            Subquery(current.values("estimate")[:1]), CharField(max_length=100)
        )
    )
    created.exclude(task_number__isnull=True).filter(Exists(first_change)).update(
        to_value=Subquery(first_change.values("from_value")[:1])
    )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0026_alter_project_type_alter_taskevent_type_sprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskevent",
            name="from_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backlog", "Backlog"),
                    ("active", "Active"),
                    ("done", "Done"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="taskevent",
            name="to_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backlog", "Backlog"),
                    ("active", "Active"),
                    ("done", "Done"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="taskevent",
            name="from_ref",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskevent",
            name="to_ref",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sprint",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_categories, migrations.RunPython.noop),
        migrations.RunPython(backfill_sprint_refs, migrations.RunPython.noop),
        migrations.RunPython(backfill_creation_estimates, migrations.RunPython.noop),
    ]
