# Generated by Django 6.1 on 2026-09-02 07:15

from django.db import migrations, models
from django.db.models import OuterRef, Subquery, Value
from django.db.models.functions import Coalesce


def backfill_categories(apps, schema_editor):
    """Resolve the snapshotted status names against each project's current
    columns, one correlated UPDATE per side. Best effort: an event naming a
    column that has since been renamed or deleted stays blank, and
    COMPLETED events land on "done" regardless - that is what the type
    means."""
    TaskStatus = apps.get_model("projects", "TaskStatus")
    TaskEvent = apps.get_model("projects", "TaskEvent")
    events = TaskEvent.objects.using(schema_editor.connection.alias)
    for side in ("from", "to"):
        category = TaskStatus.objects.filter(
            project_id=OuterRef("project_id"), name=OuterRef(f"{side}_status")
        ).values("category")[:1]
        events.exclude(**{f"{side}_status": ""}).update(
            **{f"{side}_category": Coalesce(Subquery(category), Value(""))}
        )
    events.filter(type="completed").exclude(to_status="").update(to_category="done")


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_alter_project_type_alter_taskevent_type_sprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskevent",
            name="from_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backlog", "Backlog"),
                    ("active", "Active"),
                    ("done", "Done"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="taskevent",
            name="to_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backlog", "Backlog"),
                    ("active", "Active"),
                    ("done", "Done"),
                ],
                default="",
                max_length=8,
            ),
        ),
        migrations.RunPython(backfill_categories, migrations.RunPython.noop),
    ]
