# Generated by Django 6.1.1 on 2026-09-12 10:20

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0053_folder_share_links'),
        ('projects', '0027_taskevent_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('commented', 'Commented'), ('estimate', 'Estimated'), ('epic', 'Epic'), ('sprint', 'Sprint'), ('attached', 'Attached'), ('detached', 'Detached'), ('linked', 'Linked'), ('unlinked', 'Unlinked'), ('file_linked', 'File linked'), ('file_unlinked', 'File unlinked')], max_length=13),
        ),
        migrations.CreateModel(
            name='TaskFileLink',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='files.file')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_links', to='projects.task')),
            ],
            options={
                'ordering': ['created_at', 'uuid'],
                'constraints': [models.UniqueConstraint(fields=('task', 'file'), name='unique_task_file_link')],
            },
        ),
    ]
