# Generated by Django 6.1.1 on 2026-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_taskevent_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
