# Generated by Django 6.1.1 on 2026-09-12 10:57

import django.db.models.deletion
from django.db import migrations, models

import workspace.common.uuids


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_taskevent_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("assigned", "Assigned"),
                    ("moved", "Moved"),
                    ("completed", "Completed"),
                    ("deleted", "Deleted"),
                    ("commented", "Commented"),
                    ("estimate", "Estimated"),
                    ("epic", "Epic"),
                    ("sprint", "Sprint"),
                    ("milestone", "Milestone"),
                    ("attached", "Attached"),
                    ("detached", "Detached"),
                    ("linked", "Linked"),
                    ("unlinked", "Unlinked"),
                ],
                max_length=9,
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("target_date", models.DateField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["target_date", "name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="projects.milestone",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_milestone_name_per_project"
            ),
        ),
    ]
