# Generated by Django 6.1.1 on 2026-09-13 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_taskevent_snapshots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", True),
                    ("due_date__isnull", True),
                    ("start_date__lte", models.F("due_date")),
                    _connector="OR",
                ),
                name="task_start_not_after_due",
            ),
        ),
    ]
