# Generated by Django 6.0.7 on 2026-08-15 17:46

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIdentity',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kdf_algo', models.CharField(default='argon2id', max_length=16)),
                ('kdf_params', models.JSONField(default=dict)),
                ('kdf_salt', models.TextField()),
                ('kex_public', models.TextField()),
                ('sig_public', models.TextField()),
                ('wrapped_kex_priv', models.TextField()),
                ('wrapped_sig_priv', models.TextField()),
                ('sig_over_kex_pub', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'account identities',
            },
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_name', models.TextField()),
                ('encrypted_description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='lock', max_length=64)),
                ('color', models.CharField(default='primary', max_length=32)),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('encrypt_uris', models.BooleanField(default=True)),
                ('metadata_sig', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('login', 'Login')], default='login', max_length=32)),
                ('is_favorite', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_name', models.TextField()),
                ('encrypted_notes', models.TextField(blank=True, default='')),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('entry_version', models.PositiveIntegerField(default=1)),
                ('metadata_sig', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vault.vault')),
            ],
            options={
                'verbose_name_plural': 'vault entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryField',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('field_id', models.CharField(max_length=64)),
                ('encrypted_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='vault.vaultentry')),
            ],
        ),
        migrations.CreateModel(
            name='VaultFolder',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_name', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vault.vaultfolder')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='vault.vault')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='vault.vaultfolder'),
        ),
        migrations.CreateModel(
            name='VaultKeyWrap',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('wrapped_key', models.TextField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('hpke_suite', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_key_wraps', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_wraps', to='vault.vault')),
            ],
        ),
        migrations.CreateModel(
            name='VaultTag',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_name', models.TextField()),
                ('color', models.CharField(default='neutral', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='vault.vault')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='vault.vaulttag'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['owner', 'created_at'], name='vault_vault_owner_i_7404b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryfield',
            constraint=models.UniqueConstraint(fields=('entry', 'field_id'), name='unique_entry_field_id'),
        ),
        migrations.AddConstraint(
            model_name='entryfield',
            constraint=models.CheckConstraint(condition=models.Q(('field_id__in', ('name', 'notes')), _negated=True), name='entry_field_id_not_reserved'),
        ),
        migrations.AddIndex(
            model_name='vaultfolder',
            index=models.Index(fields=['vault', 'parent'], name='vault_vault_vault_i_5c6650_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultkeywrap',
            index=models.Index(fields=['recipient'], name='vault_vault_recipie_ebe9cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='vaultkeywrap',
            constraint=models.UniqueConstraint(fields=('vault', 'recipient'), name='unique_vault_key_wrap_per_recipient'),
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['vault', 'deleted_at'], name='vault_vault_vault_i_9d69ab_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['vault', 'folder'], name='vault_vault_vault_i_dd959e_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['vault', 'is_favorite'], name='vault_vault_vault_i_ad1917_idx'),
        ),
    ]
