# Generated by Django 6.0.7 on 2026-08-15 17:45

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIdentity',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kdf_algo', models.CharField(default='argon2id', max_length=16)),
                ('kdf_params', models.JSONField(default=dict)),
                ('kdf_salt', models.TextField()),
                ('kex_public', models.TextField()),
                ('sig_public', models.TextField()),
                ('wrapped_kex_priv', models.TextField()),
                ('wrapped_sig_priv', models.TextField()),
                ('sig_over_kex_pub', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'account identities',
            },
        ),
    ]
