# Generated by Django 6.1 on 2026-08-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vault.vaultentry',),
        ),
        migrations.CreateModel(
            name='LoginEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vault.typedentry',),
        ),
    ]
