from django.urls import path

from .views import (
    accounts,
    attachments,
    compose,
    contacts,
    extractions,
    folders,
    labels,
    messages,
    oauth2,
    rules,
)

urlpatterns = [
    path(
        "api/v1/mail/autodiscover",
        accounts.MailAutodiscoverView.as_view(),
        name="mail-autodiscover",
    ),
    path(
        "api/v1/mail/accounts",
        accounts.MailAccountListView.as_view(),
        name="mail-account-list",
    ),
    path(
        "api/v1/mail/accounts/<uuid:uuid>",
        accounts.MailAccountDetailView.as_view(),
        name="mail-account-detail",
    ),
    path(
        "api/v1/mail/accounts/<uuid:uuid>/test",
        accounts.MailAccountTestView.as_view(),
        name="mail-account-test",
    ),
    path(
        "api/v1/mail/accounts/<uuid:uuid>/sync",
        accounts.MailAccountSyncView.as_view(),
        name="mail-account-sync",
    ),
    path(
        "api/v1/mail/labels",
        labels.MailLabelListView.as_view(),
        name="mail-label-list",
    ),
    path(
        "api/v1/mail/labels/<uuid:uuid>",
        labels.MailLabelDetailView.as_view(),
        name="mail-label-detail",
    ),
    path(
        "api/v1/mail/rules",
        rules.MailRuleListView.as_view(),
        name="mail-rule-list",
    ),
    path(
        "api/v1/mail/rules/<uuid:uuid>",
        rules.MailRuleDetailView.as_view(),
        name="mail-rule-detail",
    ),
    path(
        "api/v1/mail/rules/<uuid:uuid>/reorder",
        rules.MailRuleReorderView.as_view(),
        name="mail-rule-reorder",
    ),
    path(
        "api/v1/mail/rules/<uuid:uuid>/apply",
        rules.MailRuleApplyView.as_view(),
        name="mail-rule-apply",
    ),
    path(
        "api/v1/mail/rules/test",
        rules.MailRuleTestView.as_view(),
        name="mail-rule-test",
    ),
    path(
        "api/v1/mail/rules/<uuid:uuid>/logs",
        rules.MailRuleLogsView.as_view(),
        name="mail-rule-logs",
    ),
    path(
        "api/v1/mail/folders",
        folders.MailFolderListView.as_view(),
        name="mail-folder-list",
    ),
    path(
        "api/v1/mail/folders/<uuid:uuid>",
        folders.MailFolderUpdateView.as_view(),
        name="mail-folder-update",
    ),
    path(
        "api/v1/mail/folders/<uuid:uuid>/mark-read",
        folders.MailFolderMarkReadView.as_view(),
        name="mail-folder-mark-read",
    ),
    path(
        "api/v1/mail/contacts/autocomplete",
        contacts.ContactAutocompleteView.as_view(),
        name="mail-contact-autocomplete",
    ),
    path(
        "api/v1/mail/messages",
        messages.MailMessageListView.as_view(),
        name="mail-message-list",
    ),
    path("api/v1/mail/drafts", compose.MailDraftView.as_view(), name="mail-draft"),
    path(
        "api/v1/mail/drafts/<uuid:uuid>",
        compose.MailDraftView.as_view(),
        name="mail-draft-detail",
    ),
    path(
        "api/v1/mail/messages/send",
        compose.MailSendView.as_view(),
        name="mail-send",
    ),
    path(
        "api/v1/mail/messages/batch-action",
        messages.MailBatchActionView.as_view(),
        name="mail-batch-action",
    ),
    path(
        "api/v1/mail/messages/<uuid:uuid>/labels",
        labels.MailMessageLabelView.as_view(),
        name="mail-message-labels",
    ),
    path(
        "api/v1/mail/messages/<uuid:uuid>",
        messages.MailMessageDetailView.as_view(),
        name="mail-message-detail",
    ),
    path(
        "api/v1/mail/extractions/<uuid:extraction_id>",
        extractions.ExtractionDetailView.as_view(),
        name="mail-extraction-detail",
    ),
    path(
        "api/v1/mail/attachments/<uuid:uuid>",
        attachments.MailAttachmentDownloadView.as_view(),
        name="mail-attachment-download",
    ),
    path(
        "api/v1/mail/attachments/<uuid:uuid>/save-to-files",
        attachments.MailAttachmentSaveToFilesView.as_view(),
        name="mail-attachment-save-to-files",
    ),
    path(
        "api/v1/mail/oauth2/providers",
        oauth2.OAuthProvidersView.as_view(),
        name="mail-oauth2-providers",
    ),
    path(
        "api/v1/mail/oauth2/authorize",
        oauth2.OAuthAuthorizeView.as_view(),
        name="mail-oauth2-authorize",
    ),
]
