from django.urls import path

from .views import account, entries, folders, tags, vaults

urlpatterns = [
    path(
        "api/v1/vault/account/init",
        account.AccountInitView.as_view(),
        name="vault-account-init",
    ),
    path(
        "api/v1/vault/account/finalize",
        account.AccountFinalizeView.as_view(),
        name="vault-account-finalize",
    ),
    path(
        "api/v1/vault/account/envelope",
        account.AccountEnvelopeView.as_view(),
        name="vault-account-envelope",
    ),
    path(
        "api/v1/vault/account/rotate",
        account.AccountRotateView.as_view(),
        name="vault-account-rotate",
    ),
    path(
        "api/v1/vault/vaults",
        vaults.VaultListView.as_view(),
        name="vault-list",
    ),
    path(
        "api/v1/vault/vaults/<uuid:uuid>",
        vaults.VaultDetailView.as_view(),
        name="vault-detail",
    ),
    path(
        "api/v1/vault/folders",
        folders.FolderListView.as_view(),
        name="vault-folder-list",
    ),
    path(
        "api/v1/vault/folders/<uuid:uuid>",
        folders.FolderDetailView.as_view(),
        name="vault-folder-detail",
    ),
    path(
        "api/v1/vault/folders/<uuid:uuid>/delete",
        folders.FolderDeleteView.as_view(),
        name="vault-folder-delete",
    ),
    path(
        "api/v1/vault/tags",
        tags.TagListView.as_view(),
        name="vault-tag-list",
    ),
    path(
        "api/v1/vault/tags/<uuid:uuid>",
        tags.TagDetailView.as_view(),
        name="vault-tag-detail",
    ),
    path(
        "api/v1/vault/entries",
        entries.EntryListView.as_view(),
        name="vault-entry-list",
    ),
    path(
        "api/v1/vault/entries/<uuid:uuid>",
        entries.EntryDetailView.as_view(),
        name="vault-entry-detail",
    ),
    path(
        "api/v1/vault/entries/<uuid:uuid>/restore",
        views_entries.EntryRestoreView.as_view(),
        name="vault-entry-restore",
    ),
    path(
        "api/v1/vault/entries/<uuid:uuid>/purge",
        views_entries.EntryPurgeView.as_view(),
        name="vault-entry-purge",
    ),
]
