import logging

from django.db import transaction
from django.utils import timezone

from workspace.ai.services.llm import clean_llm_content

logger = logging.getLogger(__name__)


def _describe_image(data):
    """Return (label, mime_type, category, extension) for generated image bytes.

    Image backends return whatever format their model produces -- PNG, JPEG or
    WebP -- regardless of what was requested, so the type is read from the bytes
    instead of assumed.
    """
    from workspace.files.services.detection import detect_from_bytes, get_label_info

    detection = detect_from_bytes(data)
    if detection.group != "image":
        # Magika could not place the bytes in the image group. Keep the PNG
        # assumption rather than storing them as an opaque blob, which would
        # drop the attachment out of the media gallery and the image viewer.
        return "unknown", "image/png", "unknown", ".png"
    extensions = get_label_info(detection.label).get("extensions") or ["png"]
    return detection.label, detection.mime_type, detection.group, f".{extensions[0]}"


@transaction.atomic
def post_bot_message(
    conversation,
    bot_user,
    result,
    tool_context,
    ai_task,
    raw_messages=None,
    tool_data=None,
):
    """Create the bot message, attach images, update unread counts, notify, and complete AITask.

    Returns (body, bot_message).
    """
    from django.core.files.base import ContentFile

    from workspace.chat.models import (
        Message,
        MessageAttachment,
        MessageInteraction,
    )
    from workspace.chat.services.posting import deliver_message
    from workspace.chat.services.rendering import render_message_body

    body = clean_llm_content(result["content"])
    body_html = render_message_body(body)

    # Reasoning of the final completion is not captured by run_tool_loop,
    # which only records rounds that executed tools. Append it as a tool-less
    # round so the UI timeline can show it. Skip when it duplicates the last
    # round's thinking: on the stop_after_round path the posted result IS the
    # last tool round.
    thinking = (result.get("thinking") or "").strip()
    if thinking and not (tool_data and tool_data[-1].get("thinking") == thinking):
        tool_data = [
            *(tool_data or []),
            {"thinking": thinking, "tool_calls": [], "results": []},
        ]

    bot_message = Message.objects.create(
        conversation_id=conversation.pk,
        author=bot_user,
        body=body,
        body_html=body_html,
        tool_data=tool_data,
    )

    # If a tool wrote tool_context['question'] (currently only the
    # ask_user_question tool does this), persist it as an interactive UI
    # block attached to the bot message. The surrounding @transaction.atomic
    # decorator on post_bot_message guarantees both rows commit together.
    question = tool_context.get("question")
    if question:
        MessageInteraction.objects.create(
            message=bot_message,
            kind=MessageInteraction.Kind.QUESTION,
            payload=question,
        )

    # Attach any images generated by tools during this response
    pending = tool_context.get("images", [])
    created_attachments = []
    for i, img in enumerate(pending):
        data = img["data"]
        label, mime_type, category, extension = _describe_image(data)
        slug = img.get("prompt", "image")[:60].strip().replace(" ", "_")
        slug = "".join(c for c in slug if c.isalnum() or c in "_-")
        suffix = f"_{i + 1}" if len(pending) > 1 else ""
        filename = f"{slug}{suffix}{extension}"
        att = MessageAttachment(
            message=bot_message,
            original_name=filename,
            mime_type=mime_type,
            type=label,
            category=category,
            size=len(data),
        )
        att.file.save(filename, ContentFile(data), save=False)
        att.save()
        created_attachments.append(att)

    if created_attachments:
        from workspace.ai.tasks.captions import enqueue_caption_if_image

        transaction.on_commit(
            lambda atts=created_attachments: [enqueue_caption_if_image(a) for a in atts]
        )

    deliver_message(conversation, bot_message)

    ai_task.status = ai_task.Status.COMPLETED
    ai_task.result = body
    ai_task.chat_message = bot_message
    ai_task.model_used = result["model"]
    ai_task.prompt_tokens = result["prompt_tokens"]
    ai_task.completion_tokens = result["completion_tokens"]
    ai_task.raw_messages = raw_messages
    ai_task.completed_at = timezone.now()
    ai_task.save()

    return body, bot_message


@transaction.atomic
def handle_generation_error(conversation, bot_user, ai_task, error):
    """Handle a failed bot response: post error message, update counts, notify."""
    from workspace.chat.models import Message
    from workspace.chat.services.posting import deliver_message
    from workspace.chat.services.rendering import render_message_body

    # Detailed error stays on AITask + logs; the chat sees a generic message so
    # we don't leak provider/backend/user data into the conversation body.
    ai_task.status = ai_task.Status.FAILED
    ai_task.error = str(error)
    ai_task.completed_at = timezone.now()
    ai_task.save()
    logger.warning(
        "Bot generation failed for conversation=%s: %s", conversation.pk, error
    )

    error_body = (
        "⚠️ Sorry, I encountered an error generating a response. Please try again."
    )
    error_html = render_message_body(error_body)
    error_message = Message.objects.create(
        conversation_id=conversation.pk,
        author=bot_user,
        body=error_body,
        body_html=error_html,
    )
    deliver_message(conversation, error_message)
