import logging

from django.db import transaction
from django.utils import timezone

from workspace.ai.services.llm import clean_llm_content
from workspace.ai.services.tool_loop import render_tool_badges

logger = logging.getLogger(__name__)


@transaction.atomic
def post_bot_message(conversation, bot_user, result, used_tools, tool_context, ai_task, raw_messages=None, tool_data=None):
    """Create the bot message, attach images, update unread counts, notify, and complete AITask.

    Returns (body, bot_message).
    """
    from django.core.files.base import ContentFile
    from django.db.models import F

    from workspace.chat.models import ConversationMember, Message, MessageAttachment
    from workspace.chat.services.notifications import notify_conversation_members
    from workspace.chat.services.rendering import render_message_body

    body = clean_llm_content(result['content'])
    body_html = render_message_body(body)

    if used_tools:
        body_html += render_tool_badges(used_tools)

    bot_message = Message.objects.create(
        conversation_id=conversation.pk,
        author=bot_user,
        body=body,
        body_html=body_html,
        tool_data=tool_data,
    )

    # Attach any images generated by tools during this response
    pending = tool_context.get('images', [])
    for i, img in enumerate(pending):
        slug = img.get('prompt', 'image')[:60].strip().replace(' ', '_')
        slug = ''.join(c for c in slug if c.isalnum() or c in '_-')
        suffix = f'_{i + 1}' if len(pending) > 1 else ''
        filename = f'{slug}{suffix}.png'
        att = MessageAttachment(
            message=bot_message,
            original_name=filename,
            mime_type='image/png',
            size=len(img['data']),
        )
        att.file.save(filename, ContentFile(img['data']), save=False)
        att.save()

    ConversationMember.objects.filter(
        conversation_id=conversation.pk,
        left_at__isnull=True,
    ).exclude(user=bot_user).update(
        unread_count=F('unread_count') + 1,
    )

    from workspace.chat.models import Conversation as Conv
    Conv.objects.filter(pk=conversation.pk).update(updated_at=timezone.now())

    # Defer the SSE/email notification until after the surrounding transaction
    # commits — otherwise clients can observe the message before its rows are
    # visible, and a notify failure rolls back the entire write.
    transaction.on_commit(
        lambda: notify_conversation_members(conversation, exclude_user=bot_user)
    )

    ai_task.status = ai_task.Status.COMPLETED
    ai_task.result = body
    ai_task.chat_message = bot_message
    ai_task.model_used = result['model']
    ai_task.prompt_tokens = result['prompt_tokens']
    ai_task.completion_tokens = result['completion_tokens']
    ai_task.raw_messages = raw_messages
    ai_task.completed_at = timezone.now()
    ai_task.save()

    return body, bot_message


@transaction.atomic
def handle_generation_error(conversation, bot_user, ai_task, error):
    """Handle a failed bot response: post error message, update counts, notify."""
    from django.db.models import F

    from workspace.chat.models import ConversationMember, Message
    from workspace.chat.services.notifications import notify_conversation_members
    from workspace.chat.services.rendering import render_message_body

    # Detailed error stays on AITask + logs; the chat sees a generic message so
    # we don't leak provider/backend/user data into the conversation body.
    ai_task.status = ai_task.Status.FAILED
    ai_task.error = str(error)
    ai_task.completed_at = timezone.now()
    ai_task.save()
    logger.warning('Bot generation failed for conversation=%s: %s', conversation.pk, error)

    error_body = "⚠️ Sorry, I encountered an error generating a response. Please try again."
    error_html = render_message_body(error_body)
    Message.objects.create(
        conversation_id=conversation.pk,
        author=bot_user,
        body=error_body,
        body_html=error_html,
    )
    ConversationMember.objects.filter(
        conversation_id=conversation.pk,
        left_at__isnull=True,
    ).exclude(user=bot_user).update(
        unread_count=F('unread_count') + 1,
    )
    from workspace.chat.models import Conversation as Conv
    Conv.objects.filter(pk=conversation.pk).update(updated_at=timezone.now())
    transaction.on_commit(
        lambda: notify_conversation_members(conversation, exclude_user=bot_user)
    )
