# Generated by Django 6.0 on 2026-01-30 21:04

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module', 'key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'module', 'key'), name='unique_user_module_key')],
            },
        ),
    ]
