# Generated by Django 6.0.2 on 2026-02-17 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='presence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_seen', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'User presence',
                'verbose_name_plural': 'User presences',
            },
        ),
    ]
