# Generated by Django 6.0.2 on 2026-02-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='manual_status',
            field=models.CharField(choices=[('auto', 'Auto'), ('online', 'Online'), ('away', 'Away'), ('busy', 'Busy'), ('invisible', 'Invisible')], default='auto', max_length=16),
        ),
    ]
