# Generated by Django 6.0.2 on 2026-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpresence_manual_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpresence',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
