# Generated by Django 6.0.3 on 2026-03-28 09:18

from django.db import migrations


def remove_expanded_folders(apps, schema_editor):
    db = schema_editor.connection.alias
    UserSetting = apps.get_model('users', 'UserSetting')
    for setting in UserSetting.objects.using(db).filter(module='notes', key='preferences'):
        value = setting.value
        if isinstance(value, dict) and 'expandedFolders' in value:
            del value['expandedFolders']
            setting.value = value
            setting.save(update_fields=['value'], using=db)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_last_activity'),
    ]

    operations = [
        migrations.RunPython(remove_expanded_folders, migrations.RunPython.noop),
    ]
