# Generated by Django 6.0.3 on 2026-04-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import workspace.common.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notes_expanded_folders_pref'),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APITokenLabel',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('auth_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to=settings.KNOX_TOKEN_MODEL)),
            ],
            options={
                'ordering': ['-auth_token__created'],
            },
        ),
    ]
