# Generated by Django 6.0.4 on 2026-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_apitokenlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='module',
            field=models.CharField(max_length=64),
        ),
    ]
