# Generated by Django 6.1 on 2026-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_disable_oidc_linked_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcidentity',
            name='synced_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
