# Generated by Django 6.0.2 on 2026-02-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
