# Generated by Django 6.0.4 on 2026-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_notif_rcpt_origin_read'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pushsubscription',
            name='notificatio_user_id_d7f78b_idx',
        ),
    ]
