# Generated by Django 6.0.7 on 2026-08-03 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar", "0016_event_timezone_and_allday_normalization"),
        ("chat", "0024_messageattachment_ai_description"),
        ("files", "0039_thumbnailfailure"),
        ("notifications", "0006_notification_partial_unread"),
        ("projects", "0015_alter_taskevent_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="chat.conversation",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="calendar.event",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="files.file",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="poll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="calendar.poll",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="projects.task",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("conversation__isnull", True),
                        ("event__isnull", True),
                        ("file__isnull", True),
                        ("poll__isnull", True),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("conversation__isnull", False),
                        ("event__isnull", True),
                        ("file__isnull", True),
                        ("poll__isnull", True),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("conversation__isnull", True),
                        ("event__isnull", True),
                        ("file__isnull", False),
                        ("poll__isnull", True),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("conversation__isnull", True),
                        ("event__isnull", True),
                        ("file__isnull", True),
                        ("poll__isnull", True),
                        ("task__isnull", False),
                    ),
                    models.Q(
                        ("conversation__isnull", True),
                        ("event__isnull", False),
                        ("file__isnull", True),
                        ("poll__isnull", True),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("conversation__isnull", True),
                        ("event__isnull", True),
                        ("file__isnull", True),
                        ("poll__isnull", False),
                        ("task__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="notif_at_most_one_source",
            ),
        ),
    ]
