# Generated by Django 6.0.7 on 2026-08-12 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0016_event_timezone_and_allday_normalization'),
        ('chat', '0026_conversationmember_notification_level'),
        ('files', '0041_tag_color_hex'),
        ('mail', '0029_mailmessage_references'),
        ('notifications', '0009_delete_bot_notifications'),
        ('projects', '0015_alter_taskevent_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notif_at_most_one_source',
        ),
        migrations.AddField(
            model_name='notification',
            name='mail_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mail.mailmessage'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('conversation__isnull', False), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('conversation__isnull', True), ('event__isnull', True), ('file__isnull', False), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', False)), models.Q(('conversation__isnull', True), ('event__isnull', False), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', False), ('task__isnull', True)), models.Q(('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', False), ('poll__isnull', True), ('task__isnull', True)), _connector='OR'), name='notif_at_most_one_source'),
        ),
    ]
