# Generated by Django 6.0.7 on 2026-08-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_remove_notification_notif_at_most_one_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="stream",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
