# Generated by Django 6.1.1 on 2026-10-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0020_event_member_external_guest'),
        ('chat', '0030_name_untitled_groups'),
        ('files', '0061_file_last_event_at'),
        ('mail', '0035_mailfolder_alias_of'),
        ('notifications', '0012_remove_notification_color'),
        ('photos', '0012_hidden_files'),
        ('projects', '0029_task_file_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notif_at_most_one_source',
        ),
        migrations.AddField(
            model_name='notification',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='photos.album'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', True), ('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('album__isnull', True), ('conversation__isnull', False), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('album__isnull', True), ('conversation__isnull', True), ('event__isnull', True), ('file__isnull', False), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('album__isnull', True), ('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', False)), models.Q(('album__isnull', True), ('conversation__isnull', True), ('event__isnull', False), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), models.Q(('album__isnull', True), ('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', False), ('task__isnull', True)), models.Q(('album__isnull', True), ('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', False), ('poll__isnull', True), ('task__isnull', True)), models.Q(('album__isnull', False), ('conversation__isnull', True), ('event__isnull', True), ('file__isnull', True), ('mail_message__isnull', True), ('poll__isnull', True), ('task__isnull', True)), _connector='OR'), name='notif_at_most_one_source'),
        ),
    ]
