"""Model weights, and the real backends run on them.

The weights tests fake the download. The real-backend tests are skipped
unless PHOTOS_TEST_WEIGHTS=1: they download the weights (about 40 MB for
YuNet + SFace, 290 MB for buffalo_l) into PHOTOS_MODEL_DIR. The faces in
tests/fixtures/ were generated by a GAN: they are nobody.
"""

import hashlib
import io
import os
import tempfile
import zipfile
from pathlib import Path
from unittest import skipUnless
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings
from PIL import Image, ImageOps

from workspace.photos.models import FaceCluster
from workspace.photos.services.detection import weights
from workspace.photos.services.detection.weights import ModelFile, WeightsError
from workspace.photos.services.face_analysis import analyze_faces
from workspace.photos.services.face_grouping import cluster_owner

from .faces import FacesTestMixin, opt_in
from .images import upload

User = get_user_model()
FIXTURES = Path(__file__).parent / "fixtures"


def _sha(data):
    return hashlib.sha256(data).hexdigest()


class WeightsTests(TestCase):
    def setUp(self):
        self.dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.dir.cleanup)
        override = override_settings(PHOTOS_MODEL_DIR=self.dir.name)
        override.enable()
        self.addCleanup(override.disable)
        weights._verified.clear()
        self.addCleanup(weights._verified.clear)

    def _serving(self, payloads):
        """Patch the download to serve *payloads* by URL; return the call log."""
        calls = []

        def fetch(url, target):
            calls.append(url)
            target.write_bytes(payloads[url])
            return _sha(payloads[url])

        patcher = patch.object(weights, "_fetch", side_effect=fetch)
        patcher.start()
        self.addCleanup(patcher.stop)
        return calls

    def test_downloads_a_missing_model_and_checks_its_hash(self):
        data = b"model bytes"
        self._serving({"https://x/model.onnx": data})
        model = ModelFile(
            name="model.onnx", sha256=_sha(data), url="https://x/model.onnx"
        )

        path = weights.ensure(model)

        self.assertEqual(path.read_bytes(), data)

    def test_refuses_a_download_that_does_not_match_its_hash(self):
        self._serving({"https://x/model.onnx": b"tampered"})
        model = ModelFile(
            name="model.onnx", sha256=_sha(b"genuine"), url="https://x/model.onnx"
        )

        with self.assertRaises(WeightsError):
            weights.ensure(model)
        self.assertFalse(weights.model_path(model).exists())

    def test_refuses_a_file_on_disk_that_does_not_match_its_hash(self):
        model = ModelFile(name="model.onnx", sha256=_sha(b"genuine"), url="https://x/m")
        weights.model_path(model).write_bytes(b"truncated")

        with self.assertRaises(WeightsError):
            weights.ensure(model)

    def test_extracts_every_member_of_an_archive_from_one_download(self):
        det, rec = b"detector", b"recognizer"
        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as archive:
            archive.writestr("det.onnx", det)
            archive.writestr("rec.onnx", rec)
        pack = buffer.getvalue()
        calls = self._serving({"https://x/pack.zip": pack})
        models = [
            ModelFile(
                name=f"pack/{member}",
                sha256=_sha(content),
                url="https://x/pack.zip",
                archive_member=member,
                archive_sha256=_sha(pack),
            )
            for member, content in (("det.onnx", det), ("rec.onnx", rec))
        ]

        weights.ensure_all(models)

        self.assertEqual(calls, ["https://x/pack.zip"])
        self.assertEqual(weights.model_path(models[0]).read_bytes(), det)
        self.assertEqual(weights.model_path(models[1]).read_bytes(), rec)


def _photo(path, *, mirror=False, crop=0):
    image = Image.open(path).convert("RGB")
    if crop:
        image = image.crop(
            (crop, crop, image.width - crop // 2, image.height - crop // 2)
        )
    if mirror:
        image = ImageOps.mirror(image)
    canvas = Image.new("RGB", (600, 400), (200, 190, 170))
    canvas.paste(image, (40, 60))
    buffer = io.BytesIO()
    canvas.save(buffer, format="JPEG", quality=90)
    return buffer.getvalue()


@skipUnless(os.environ.get("PHOTOS_TEST_WEIGHTS") == "1", "set PHOTOS_TEST_WEIGHTS=1")
class RealBackendTests(FacesTestMixin, TestCase):
    """Two photos of one face and one of another make two clusters."""

    def _run(self):
        user = User.objects.create_user(username="alice", password="p")
        opt_in(user)
        for name, data in (
            ("a-1.jpg", _photo(FIXTURES / "synthetic-face-a.jpg")),
            (
                "a-2.jpg",
                _photo(FIXTURES / "synthetic-face-a.jpg", mirror=True, crop=24),
            ),
            ("b.jpg", _photo(FIXTURES / "synthetic-face-b.jpg")),
        ):
            self.assertEqual(len(analyze_faces(upload(user, name, data))), 1, name)
        cluster_owner(user.pk)
        return sorted(
            sorted(cluster.faces.values_list("file__name", flat=True))
            for cluster in FaceCluster.objects.filter(owner=user)
        )

    @override_settings(PHOTOS_FACES_ENABLED=True, PHOTOS_FACE_BACKEND="yunet_sface")
    def test_yunet_sface(self):
        self.assertEqual(self._run(), [["a-1.jpg", "a-2.jpg"], ["b.jpg"]])

    @override_settings(PHOTOS_FACES_ENABLED=True, PHOTOS_FACE_BACKEND="scrfd_arcface")
    def test_scrfd_arcface(self):
        from workspace.photos.indexes import FACE_EMBEDDINGS

        if FACE_EMBEDDINGS.dims != 512:
            self.skipTest("the index is declared for another backend's size")
        self.assertEqual(self._run(), [["a-1.jpg", "a-2.jpg"], ["b.jpg"]])
