# Generated by Django 6.0.2 on 2026-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_create_default_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('summarize', 'Summarize'), ('compose', 'Compose'), ('reply', 'Reply'), ('chat', 'Chat'), ('editor', 'Editor')], max_length=20),
        ),
    ]
