# Generated by Django 6.0.2 on 2026-03-05 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_usermemory'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_bots', to='auth.group'),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_bots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
