# Generated by Django 6.0.2 on 2026-03-05 22:07

from django.db import migrations


def set_existing_bots_public(apps, schema_editor):
    BotProfile = apps.get_model('ai', 'BotProfile')
    BotProfile.objects.all().update(is_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_bot_permissions'),
    ]

    operations = [
        migrations.RunPython(set_existing_bots_public, migrations.RunPython.noop),
    ]
