# Generated by Django 6.0.2 on 2026-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_set_existing_bots_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='supports_tools',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='supports_vision',
            field=models.BooleanField(default=True),
        ),
    ]
