# Generated by Django 6.0.2 on 2026-03-07 17:41

import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_add_bot_capability_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='uuid',
            field=models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False),
        ),
    ]
