# Generated by Django 6.0.3 on 2026-03-09 19:47

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_aitask_uuid'),
        ('chat', '0011_attachment_file_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('kind', models.CharField(choices=[('once', 'Once'), ('recurring', 'Recurring')], max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_unit', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='', max_length=10)),
                ('recurrence_interval', models.PositiveIntegerField(default=1)),
                ('recurrence_time', models.TimeField(blank=True, null=True)),
                ('recurrence_day', models.PositiveIntegerField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_scheduled_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='chat.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
    ]
