# Generated by Django 6.0.3 on 2026-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_aitask_raw_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('summarize', 'Summarize'), ('compose', 'Compose'), ('reply', 'Reply'), ('chat', 'Chat'), ('editor', 'Editor'), ('classify', 'Classify')], max_length=20),
        ),
    ]
