# Generated by Django 6.0.3 on 2026-03-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_aitask_task_type'),
        ('chat', '0011_attachment_file_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_summary_obj', serialize=False, to='chat.conversation')),
                ('content', models.TextField(blank=True, default='')),
                ('up_to', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
