# Generated by Django 6.0.4 on 2026-04-13 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_conversation_summary'),
        ('chat', '0014_linkpreview_messagelinkpreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='aitask_owner_status'),
        ),
    ]
