# Generated by Django 6.0.4 on 2026-04-28 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_aitask_aitask_owner_status'),
        ('chat', '0014_linkpreview_messagelinkpreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='next_run_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['next_run_at'], name='scheduled_active_next_run'),
        ),
    ]
