# Generated by Django 6.0.5 on 2026-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_partial_scheduled_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('summarize', 'Summarize'), ('compose', 'Compose'), ('reply', 'Reply'), ('chat', 'Chat'), ('editor', 'Editor'), ('classify', 'Classify'), ('extract', 'Extract')], max_length=20),
        ),
    ]
