# Generated by Django 6.0.7 on 2026-07-26 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_alter_aitask_task_type'),
        ('chat', '0021_chat_fulltext_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['status', 'completed_at'], name='aitask_status_completed'),
        ),
    ]
