# Generated by Django 6.0.7 on 2026-08-06 12:46

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0016_aitask_aitask_status_completed"),
        ("chat", "0024_messageattachment_ai_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aitask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("summarize", "Summarize"),
                    ("compose", "Compose"),
                    ("reply", "Reply"),
                    ("chat", "Chat"),
                    ("editor", "Editor"),
                    ("classify", "Classify"),
                    ("extract", "Extract"),
                    ("agent", "Agent"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AgentGoal",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("goal", models.TextField()),
                ("notes", models.TextField(blank=True, default="")),
                ("outcome", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("next_check_at", models.DateTimeField()),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_agent_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_goals",
                        to="chat.conversation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_agent_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_check_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "active")),
                        fields=["next_check_at"],
                        name="agentgoal_active_next_check",
                    )
                ],
            },
        ),
    ]
