# Generated by Django 6.0.7 on 2026-08-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0017_alter_aitask_task_type_agentgoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentgoal",
            name="constraints",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agentgoal",
            name="reporting",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agentgoal",
            name="success_criteria",
            field=models.TextField(blank=True, default=""),
        ),
    ]
