# Generated by Django 6.1 on 2026-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_agentgoal_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='voice',
            field=models.TextField(blank=True),
        ),
    ]
