# Generated by Django 6.1 on 2026-08-26 16:06

import workspace.ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_botprofile_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='voice_ref',
            field=models.FileField(blank=True, max_length=500, upload_to=workspace.ai.models.bot_voice_reference_path, validators=[workspace.ai.models.validate_voice_reference_size]),
        ),
        migrations.AddField(
            model_name='botprofile',
            name='voice_ref_text',
            field=models.TextField(blank=True),
        ),
    ]
