# Generated by Django 6.1 on 2026-08-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0021_botprofile_voice_ref_botprofile_voice_ref_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botprofile',
            name='voice',
        ),
    ]
