# Generated by Django 6.1 on 2026-08-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0022_remove_botprofile_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="can_send_email",
            field=models.BooleanField(default=False),
        ),
    ]
