from django.urls import path
from rest_framework.routers import SimpleRouter

from .views import (
    actions,
    album_files,
    album_links,
    album_sharing,
    albums,
    faces,
    hidden,
    import_folder,
)

router = SimpleRouter(trailing_slash=False)
router.register(
    r"api/v1/photos/clusters", faces.FaceClusterViewSet, basename="photos-cluster"
)
router.register(r"api/v1/photos/faces", faces.FaceViewSet, basename="photos-face")

urlpatterns = [
    path(
        "api/v1/photos/albums",
        albums.AlbumListView.as_view(),
        name="photo-albums",
    ),
    path(
        "api/v1/photos/albums/actions",
        actions.AlbumActionsView.as_view(),
        name="photo-album-actions",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>",
        albums.AlbumDetailView.as_view(),
        name="photo-album-detail",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/items",
        albums.AlbumItemsView.as_view(),
        name="photo-album-items",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/items/remove",
        albums.AlbumItemsRemoveView.as_view(),
        name="photo-album-items-remove",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/reorder",
        albums.AlbumReorderView.as_view(),
        name="photo-album-reorder",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/shares",
        album_sharing.AlbumSharesView.as_view(),
        name="photo-album-shares",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/leave",
        album_sharing.AlbumLeaveView.as_view(),
        name="photo-album-leave",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/links",
        album_sharing.AlbumLinksView.as_view(),
        name="photo-album-links",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/links/<uuid:link_uuid>",
        album_sharing.AlbumLinkDetailView.as_view(),
        name="photo-album-link-detail",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/download",
        album_files.AlbumDownloadView.as_view(),
        name="photo-album-download",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/files/<uuid:file_uuid>/thumbnail",
        album_files.AlbumFileThumbnailView.as_view(),
        name="photo-album-file-thumbnail",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/files/<uuid:file_uuid>/content",
        album_files.AlbumFileContentView.as_view(),
        name="photo-album-file-content",
    ),
    path(
        "api/v1/photos/albums/<uuid:uuid>/files/<uuid:file_uuid>/download",
        album_files.AlbumFileDownloadView.as_view(),
        name="photo-album-file-download",
    ),
    path(
        "api/v1/photos/shared/<str:token>/verify",
        album_links.AlbumLinkVerifyView.as_view(),
        name="photo-album-link-verify",
    ),
    path(
        "api/v1/photos/shared/<str:token>/download",
        album_links.AlbumLinkArchiveView.as_view(),
        name="photo-album-link-archive",
    ),
    path(
        "api/v1/photos/shared/<str:token>/files/<uuid:file_uuid>/thumbnail",
        album_links.AlbumLinkThumbnailView.as_view(),
        name="photo-album-link-thumbnail",
    ),
    path(
        "api/v1/photos/shared/<str:token>/files/<uuid:file_uuid>/content",
        album_links.AlbumLinkContentView.as_view(),
        name="photo-album-link-content",
    ),
    path(
        "api/v1/photos/shared/<str:token>/files/<uuid:file_uuid>/download",
        album_links.AlbumLinkDownloadView.as_view(),
        name="photo-album-link-download",
    ),
    path(
        "api/v1/photos/hidden",
        hidden.HiddenFilesView.as_view(),
        name="photos-hidden",
    ),
    path(
        "api/v1/photos/hidden/remove",
        hidden.HiddenFilesRemoveView.as_view(),
        name="photos-hidden-remove",
    ),
    path(
        "api/v1/photos/hidden/folders",
        hidden.HiddenFoldersView.as_view(),
        name="photos-hidden-folders",
    ),
    path(
        "api/v1/photos/import-folder",
        import_folder.ImportFolderView.as_view(),
        name="photos-import-folder",
    ),
    path(
        "api/v1/photos/import-folder/by-date",
        import_folder.ImportByDateView.as_view(),
        name="photos-import-by-date",
    ),
    path(
        "api/v1/photos/persons",
        faces.FacePersonsView.as_view(),
        name="photos-face-persons",
    ),
    path(
        "api/v1/photos/faces/actions",
        faces.FaceActionsView.as_view(),
        name="photos-face-actions",
    ),
    path(
        "api/v1/photos/faces/batch",
        faces.FaceBatchView.as_view(),
        name="photos-face-batch",
    ),
    path(
        "api/v1/photos/faces/undo",
        faces.FaceUndoView.as_view(),
        name="photos-face-undo",
    ),
    path(
        "api/v1/photos/faces/status",
        faces.FaceStatusView.as_view(),
        name="photos-face-status",
    ),
    path(
        "api/v1/photos/faces/<uuid:pk>/crop",
        faces.FaceCropView.as_view(),
        name="photos-face-crop",
    ),
    path(
        "api/v1/photos/files/<uuid:file_uuid>/faces",
        faces.PhotoFacesView.as_view(),
        name="photos-file-faces",
    ),
    *router.urls,
]
