# Generated by Django 6.1.1 on 2026-09-23 18:03

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0056_fileshare_project_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "camera_make",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "camera_model",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("analyzed_at", models.DateTimeField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo",
                        to="files.file",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["taken_at"], name="photo_taken_at_idx")
                ],
            },
        ),
    ]
