# Generated by Django 6.1.1 on 2026-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0056_fileshare_project_target"),
        ("photos", "0002_rename_photo_mediaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaitem",
            name="codec",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="media_type",
            field=models.CharField(
                choices=[("photo", "Photo"), ("video", "Video")],
                default="photo",
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="mediaitem",
            index=models.Index(
                fields=["latitude", "longitude"], name="media_item_location_idx"
            ),
        ),
    ]
