# Generated by Django 6.1.1 on 2026-09-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_mediaitem_video_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaitem",
            name="altitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="analysis_version",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="exposure_bias",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="exposure_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="f_number",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="flash_fired",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="focal_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="focal_length_35mm",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="iso",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="lens_make",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="lens_model",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
