# Generated by Django 6.1.1 on 2026-09-26 07:23

import django.db.models.deletion
import django.utils.timezone
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("files", "0059_file_link_state"),
        ("photos", "0004_mediaitem_exif_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "sort_mode",
                    models.CharField(
                        choices=[
                            ("capture_date", "Capture date"),
                            ("manual", "Manual"),
                        ],
                        default="capture_date",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="files.file",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_albums",
                        to="auth.group",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_albums",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbumItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("position", models.BigIntegerField()),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="photos.album",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_items",
                        to="files.file",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["owner", "group"], name="photo_album_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["group"], name="photo_album_group_idx"),
        ),
        migrations.AddIndex(
            model_name="albumitem",
            index=models.Index(
                fields=["album", "position"], name="photo_album_item_pos_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="albumitem",
            constraint=models.UniqueConstraint(
                fields=("album", "file"), name="photo_album_item_unique_file"
            ),
        ),
    ]
