# Generated by Django 6.1.1 on 2026-09-26 09:32

import django.db.models.deletion
import workspace.common.uuids
from workspace.common.vectors.operations import RunVectorIndexSQL
from django.conf import settings
from django.db import migrations, models

# Printed by `manage.py vector_sql workspace.photos.indexes.FACE_EMBEDDINGS`,
# pasted as literals: the migration never imports the live declaration.
PG_FORWARD = """\
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'vector') THEN
    RETURN;
  END IF;
  CREATE EXTENSION IF NOT EXISTS vector;
  DROP INDEX IF EXISTS photos_face_embedding_hnsw;
  IF EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = to_regclass('photos_face') AND attname = 'embedding_vec'
      AND NOT attisdropped
      AND (atttypid <> 'vector'::regtype OR atttypmod <> 128)
  ) THEN
    ALTER TABLE photos_face DROP COLUMN embedding_vec;
  END IF;
  ALTER TABLE photos_face ADD COLUMN IF NOT EXISTS embedding_vec vector(128);
EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE 'pgvector is installed but may not be enabled by this role; photos_face.embedding is searched without an index';
END
$$;
"""

PG_INDEX = """\
DO $$
BEGIN
  IF to_regtype('vector') IS NULL OR NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = to_regclass('photos_face') AND attname = 'embedding_vec'
      AND NOT attisdropped
  ) THEN
    RETURN;
  END IF;
  CREATE INDEX IF NOT EXISTS photos_face_embedding_hnsw ON photos_face
    USING hnsw (embedding_vec vector_cosine_ops);
EXCEPTION WHEN undefined_object THEN
  RAISE NOTICE 'this pgvector has no hnsw index; photos_face.embedding_vec is searched exactly';
END
$$;
"""

PG_BACKFILL = {
    "table": "photos_face",
    "pk_column": "uuid",
    "source_column": "embedding",
    "column": "embedding_vec",
    "dims": 128,
}

PG_REVERSE = """\
DROP INDEX IF EXISTS photos_face_embedding_hnsw;
ALTER TABLE photos_face DROP COLUMN IF EXISTS embedding_vec;
"""

SQLITE_FORWARD = """\
DROP TABLE IF EXISTS photos_face_embedding_vec;

CREATE VIRTUAL TABLE photos_face_embedding_vec USING vec0(
  uuid text primary key,
  owner_id integer partition key,
  embedding float[128] distance_metric=cosine,
  chunk_size=64
);

INSERT INTO photos_face_embedding_vec(uuid, owner_id, embedding)
  SELECT uuid, owner_id, embedding FROM photos_face
  WHERE length(embedding) = 512 AND owner_id IS NOT NULL;
"""

SQLITE_REVERSE = """\
DROP TABLE IF EXISTS photos_face_embedding_vec;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0059_file_link_state"),
        ("photos", "0005_albums"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("box_x", models.FloatField()),
                ("box_y", models.FloatField()),
                ("box_width", models.FloatField()),
                ("box_height", models.FloatField()),
                ("landmarks", models.JSONField(default=list)),
                ("detector_score", models.FloatField()),
                ("quality", models.FloatField()),
                ("embedding", models.BinaryField(blank=True, null=True)),
                (
                    "assignment",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("crop", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="files.file",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceAnalysis",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("backend", models.CharField(max_length=32)),
                ("version", models.PositiveSmallIntegerField()),
                ("face_count", models.PositiveSmallIntegerField(default=0)),
                ("analyzed_at", models.DateTimeField()),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_analysis",
                        to="files.file",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceCluster",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("centroid", models.BinaryField(blank=True, null=True)),
                ("face_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="photos.face",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_clusters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="face",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faces",
                to="photos.facecluster",
            ),
        ),
        migrations.AddField(
            model_name="face",
            name="rejected_cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="photos.facecluster",
            ),
        ),
        migrations.AddIndex(
            model_name="facecluster",
            index=models.Index(
                fields=["owner", "hidden", "-face_count"],
                name="face_cluster_listing_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="face",
            index=models.Index(
                fields=["owner", "cluster"], name="face_owner_cluster_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="face",
            constraint=models.UniqueConstraint(
                fields=("file", "cluster"), name="face_one_per_photo_per_cluster"
            ),
        ),
        RunVectorIndexSQL(
            pg_forward=PG_FORWARD,
            pg_backfill=PG_BACKFILL,
            pg_index=PG_INDEX,
            pg_reverse=PG_REVERSE,
            sqlite_forward=SQLITE_FORWARD,
            sqlite_reverse=SQLITE_REVERSE,
        ),
    ]
