# Generated by Django 6.1.1 on 2026-09-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_source_import_uid'),
        ('photos', '0006_faces'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecluster',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person'),
        ),
    ]
