# Generated by Django 6.1.1 on 2026-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_face_cluster_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecluster',
            name='cover_chosen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
