# Generated by Django 6.1.1 on 2026-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_face_cluster_cover_chosen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='assignment',
            field=models.CharField(choices=[('auto', 'Automatic'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('hidden', 'Hidden')], default='auto', max_length=10),
        ),
    ]
