# Generated by Django 6.1.1 on 2026-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0009_face_hidden_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="face",
            name="timestamp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
