# Generated by Django 6.1.1 on 2026-10-04 09:49

import django.db.models.deletion
import workspace.common.uuids
import workspace.photos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('photos', '0012_hidden_files'),
        ('projects', '0029_task_file_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='album',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlbumLink',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=workspace.photos.models._album_link_token, max_length=44, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='photos.album')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['album', 'created_at'], name='photo_album_link_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlbumShare',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('manager', 'Manager')], default='viewer', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='photos.album')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_with_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_shares', to='auth.group')),
                ('shared_with_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_shares', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['shared_with'], name='photo_album_share_user_idx'), models.Index(fields=['shared_with_group'], name='photo_album_share_group_idx'), models.Index(fields=['shared_with_project'], name='photo_album_share_proj_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('shared_with__isnull', False), ('shared_with_group__isnull', True), ('shared_with_project__isnull', True)), models.Q(('shared_with__isnull', True), ('shared_with_group__isnull', False), ('shared_with_project__isnull', True)), models.Q(('shared_with__isnull', True), ('shared_with_group__isnull', True), ('shared_with_project__isnull', False)), _connector='OR'), name='photo_album_share_one_target'), models.UniqueConstraint(condition=models.Q(('shared_with__isnull', False)), fields=('album', 'shared_with'), name='photo_album_share_unique_user'), models.UniqueConstraint(condition=models.Q(('shared_with_group__isnull', False)), fields=('album', 'shared_with_group'), name='photo_album_share_unique_group'), models.UniqueConstraint(condition=models.Q(('shared_with_project__isnull', False)), fields=('album', 'shared_with_project'), name='photo_album_share_unique_project')],
            },
        ),
    ]
