# Generated by Django 6.1.1 on 2026-10-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0013_album_sharing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="assignment",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("hidden", "Hidden"),
                    ("duplicate", "Duplicate"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
    ]
