# Generated by Django 6.0.6 on 2026-06-12 09:23

import django.db.models.deletion
import workspace.common.uuids
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleAccessRule",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module_slug", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_access_rules",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("module_slug", "group"), name="unique_module_group_rule"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("group__isnull", True)),
                        fields=("module_slug",),
                        name="unique_global_module_rule",
                    ),
                ],
            },
        ),
    ]
