# Generated by Django 6.1.1 on 2026-09-30 16:52

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.EmailField(max_length=254)),
                ("feature", models.CharField(blank=True, default="", max_length=64)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hard_bounce", "Hard bounce"),
                            ("complaint", "Complaint"),
                            ("unsubscribed", "Unsubscribed"),
                            ("manual", "Manual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("address", "feature"),
                        name="core_email_suppression_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=workspace.common.uuids.uuid_v7_or_v4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_address", models.EmailField(max_length=254)),
                ("feature", models.CharField(max_length=64)),
                ("template", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=255)),
                ("transactional", models.BooleanField(default=True)),
                (
                    "message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("suppressed", "Suppressed"),
                            ("rate_limited", "Rate limited"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "email deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_address", "created_at"],
                        name="core_emaild_to_addr_3a7165_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_emaild_created_a35fe1_idx"
                    ),
                    models.Index(
                        fields=["feature", "created_at"],
                        name="core_emaild_feature_7e7950_idx",
                    ),
                ],
            },
        ),
    ]
