# Generated by Django 6.1 on 2026-08-19 08:14

import django.db.models.deletion
import workspace.common.uuids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConnection',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, default='', max_length=2000)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('oauth2_data_encrypted', models.BinaryField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kinds', models.JSONField(default=list)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('claim_token', models.CharField(blank=True, default='', max_length=64)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='imports.importconnection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJobItem',
            fields=[
                ('uuid', models.UUIDField(default=workspace.common.uuids.uuid_v7_or_v4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=30)),
                ('remote_id', models.TextField()),
                ('remote_etag', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10)),
                ('target_uuid', models.UUIDField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imports.importjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='importconnection',
            index=models.Index(fields=['owner', '-created_at'], name='importconn_owner_created'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='importjob_owner_status'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'finished_at'], name='importjob_status_finished'),
        ),
        migrations.AddIndex(
            model_name='importjobitem',
            index=models.Index(fields=['job', 'status'], name='importjobitem_job_status'),
        ),
        migrations.AddConstraint(
            model_name='importjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'kind', 'remote_id'), name='importjobitem_unique_entry'),
        ),
    ]
