# Generated by Django 6.1 on 2026-08-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='claim_token',
        ),
    ]
