# Generated by Django 6.1 on 2026-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_drop_claim_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('connection',), name='importjob_one_active_per_conn'),
        ),
    ]
