# Generated by Django 6.1 on 2026-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_drop_claim_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='importjobitem',
            index=models.Index(fields=['job', 'created_at'], name='importjobitem_job_created'),
        ),
        migrations.AddConstraint(
            model_name='importjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('connection',), name='importjob_one_active_per_conn'),
        ),
    ]
