"""
Django settings for Workspace project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import mimetypes
import os
from pathlib import Path

import dj_database_url

# Fix MIME types for JavaScript modules on Windows
mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("application/javascript", ".mjs", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(apvd+h#1t_@zz504ks3ek2q_4*wm!p+#!(vte70q*xru47-zj')

# SECURITY WARNING: don't run with debug turned on in production!
# Accept "1", "true", "yes" (case-insensitive) to enable; default is True for local dev
_DEBUG_ENV = os.getenv('DEBUG')
if _DEBUG_ENV is None:
    DEBUG = True
else:
    DEBUG = str(_DEBUG_ENV).lower() in {"1", "true", "yes", "on"}

# ALLOWED_HOSTS configurable via comma-separated env; default allows all in container use
_ALLOWED = os.getenv('ALLOWED_HOSTS')
if _ALLOWED:
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ["*"] if not DEBUG else []

# CSRF Configuration for production
# Allow CSRF_TRUSTED_ORIGINS to be set via env (comma-separated list)
_CSRF_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS')
if _CSRF_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _CSRF_ORIGINS.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = []

# In production behind a proxy, ensure CSRF cookies work correctly
if not DEBUG:
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'true').lower() in {'1', 'true', 'yes', 'on'}
    CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to read it if needed
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'true').lower() in {'1', 'true', 'yes', 'on'}
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Trust X-Forwarded-Proto from proxy

# Application version (from env, defaults to 'dev')
APP_VERSION = os.getenv('APP_VERSION') or 'dev'
# Recent files listing limits
RECENT_FILES_LIMIT = int(os.getenv('RECENT_FILES_LIMIT', '25'))
RECENT_FILES_MAX_LIMIT = int(os.getenv('RECENT_FILES_MAX_LIMIT', '200'))
TRASH_RETENTION_DAYS = int(os.getenv('TRASH_RETENTION_DAYS', '30'))
# Application definition

INSTALLED_APPS = [
    'django_daisy',
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'simple_history',
    # Workspace apps
    'workspace.core',
    'workspace.common',
    'workspace.files',
    'workspace.files.ui',
    'workspace.dashboard',
    'workspace.users',
    'workspace.users.ui',
    'workspace.chat',
    'workspace.chat.ui',
    'workspace.calendar',
    'workspace.calendar.ui',
    'workspace.mail',
    'workspace.mail.ui',
]

# Add Debug Toolbar only in DEBUG mode and not during tests
import sys
TESTING = 'test' in sys.argv
if DEBUG and not TESTING:
    INSTALLED_APPS.insert(
        INSTALLED_APPS.index('django.contrib.staticfiles') + 1,
        'debug_toolbar'
    )

# Cache configuration
# Default: in-memory cache for local/dev. Optional Redis via env.
_REDIS_URL = os.getenv('REDIS_URL') or os.getenv('DJANGO_REDIS_URL')
if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'TIMEOUT': None,  # Infinite by default; specific features manage their own TTL
        }
    }
    # Use Redis for session storage when available (better performance than DB)
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'Workspace-service-locmem',
            'TIMEOUT': None,
        }
    }
    # Fall back to DB sessions when Redis is not available
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # HTTP conditional GET support (ETags & Last-Modified headers for browser caching)
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Brotli compression for HTTP responses (place before GZip for better compression)
    'django_brotli.middleware.BrotliMiddleware',
    # GZip compression for HTTP responses (fallback for clients that don't support Brotli)
    'django.middleware.gzip.GZipMiddleware',
    # django-simple-history middleware to track user in history
    'simple_history.middleware.HistoryRequestMiddleware',
    # Mesure du temps de traitement pour affichage dans le footer UI et header HTTP
    # 'Workspace.common.middleware.RequestTimingMiddleware',
]

# Add Debug Toolbar middleware only in DEBUG mode and not during tests
if DEBUG and not TESTING:
    # Find the position after GZipMiddleware
    gzip_idx = MIDDLEWARE.index('django.middleware.gzip.GZipMiddleware')
    MIDDLEWARE.insert(gzip_idx + 1, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'workspace.urls'

# Disable automatic slash appending to URLs
APPEND_SLASH = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'workspace.core.context_processors.workspace_modules',
                # Expose `request_processing_ms` au template
                # 'workspace.ui.context_processors.request_timing',
            ],
            # Cache compiled templates for better performance (disabled in DEBUG mode)
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ] if not DEBUG else [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Disable BrowsableAPI renderer in production for better performance
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] if not DEBUG else [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Workspace API',
    'DESCRIPTION': (
        "Workspace productivity suite for organizing and managing daily work."
    ),
    'VERSION': APP_VERSION,
    # Ensure file uploads are correctly rendered as multipart/form-data in Swagger UI
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/v[1-9]',
    'TAGS': [
        {
            'name': 'Files',
            'description': 'Browse and manage files and folders.',
        },
        {
            'name': 'Settings',
            'description': 'Per-user, per-module key-value settings.',
        },
        {
            'name': 'Modules',
            'description': 'Workspace module registry.',
        },
        {
            'name': 'Search',
            'description': 'Unified search across workspace modules.',
        },
        {
            'name': 'Chat',
            'description': 'Real-time messaging with direct and group conversations.',
        },
        {
            'name': 'Mail',
            'description': 'Read and send emails from external mail accounts.',
        },
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'SERVE_AUTHENTICATION': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# Login/Logout URLs
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login'

# --------------------------------------------------
# Logging
# --------------------------------------------------
# Par défaut on loggue vers stdout, pour que l'orchestrateur (Docker/K8s)
# collecte les logs. Le niveau peut être contrôlé via l'env DJANGO_LOG_LEVEL.
import logging
import sys

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
            'datefmt': '%Y-%m-%dT%H:%M:%SZ',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG' if DEBUG else DJANGO_LOG_LEVEL,
            'stream': sys.stdout,
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        # Log des erreurs de requêtes Django (500, etc.)
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Log des requêtes SQL (DEBUG only)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        # REST framework
        'rest_framework': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        # Logger applicatif (utiliser logging.getLogger("workspace"))
        'workspace': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
    },
}



WSGI_APPLICATION = 'workspace.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Use DATABASE_URL for any backend:
#   sqlite:///db.sqlite3               (relative to BASE_DIR)
#   sqlite:////absolute/path/db.sqlite3
#   postgres://user:pass@host:5432/dbname
DATABASES = {
    'default': dj_database_url.config(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}', conn_max_age=60),
}

# PostgreSQL connection pooling (psycopg pool)
if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default']['OPTIONS'] = {
        **DATABASES['default'].get('OPTIONS', {}),
        'pool': True,
    }

# SQLite-specific optimizations (WAL mode, PRAGMAs)
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    try:
        Path(DATABASES['default']['NAME']).parent.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass

    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['timeout'] = 60.0
    DATABASES['default']['OPTIONS']['init_command'] = (
        "PRAGMA journal_mode=WAL; "
        "PRAGMA foreign_keys=ON; "
        "PRAGMA busy_timeout=60000; "
        "PRAGMA synchronous=NORMAL; "
        "PRAGMA temp_store=MEMORY; "
        "PRAGMA mmap_size=268435456; "
        "PRAGMA cache_size=-64000;"
    )

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Define STATIC_ROOT to avoid ImproperlyConfigured errors when using the
# staticfiles app or running collectstatic. Allow override via env var
# STATIC_ROOT; if a relative path is provided, resolve it from BASE_DIR.
_STATIC_ROOT_ENV = os.getenv('STATIC_ROOT')
if _STATIC_ROOT_ENV:
    _static_root = Path(_STATIC_ROOT_ENV)
    if not _static_root.is_absolute():
        _static_root = (BASE_DIR / _static_root).resolve()
else:
    _static_root = BASE_DIR / 'staticfiles'

STATIC_ROOT = _static_root

# Media files (user uploads)
MEDIA_ROOT = os.getenv('MEDIA_ROOT', BASE_DIR)
MEDIA_URL = '/media/'

# Storage backends (Django 5 style)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Use WhiteNoise's optimized staticfiles storage in non-debug (e.g., containers)
if not DEBUG:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-simple-history configuration
# Keep history records indefinitely (no automatic deletion)
SIMPLE_HISTORY_HISTORY_ID_USE_UUID = True  # Use UUID for history IDs
SIMPLE_HISTORY_REVERT_DISABLED = False  # Allow reverting to previous versions

# Django Debug Toolbar configuration (only active in DEBUG mode)
if DEBUG:
    import socket

    # Get local IP for Docker/VM compatibility
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [
        "127.0.0.1",
        "::1",  # IPv6 localhost (when accessing via http://localhost)
        "0.0.0.0",
    ] + [ip[: ip.rfind(".")] + ".1" for ip in ips]

    # Configuration panels to show
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',  # Most important for viewing queries
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        # Disabled: causes "Another profiling tool is already active" errors with concurrent requests
        # 'debug_toolbar.panels.profiling.ProfilingPanel',
    ]

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
        'SHOW_COLLAPSED': False,  # Toolbar expanded by default to be more visible
    }

# Celery Configuration
# Use Redis as broker if available, otherwise fall back to in-memory (not recommended for production)
CELERY_BROKER_URL = _REDIS_URL or 'memory://'
import kombu
CELERY_TASK_QUEUES = [kombu.Queue('celery')]
CELERY_RESULT_BACKEND = _REDIS_URL or 'cache+memory://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# In development, run tasks synchronously in the current thread (no worker needed)
if DEBUG:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

# Celery Beat schedule for periodic tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'sync-all-user-files': {
        'task': 'files.sync_all_users',
        'schedule': 600.0,  # Every 10 minutes
    },
    'generate-thumbnails': {
        'task': 'files.generate_thumbnails',
        'schedule': 300.0,  # Every 5 minutes
    },
    'purge-trash': {
        'task': 'files.purge_trash',
        'schedule': crontab(hour=2, minute=30),  # Every day at 2:30 AM
    },
    'db-maintenance': {
        'task': 'core.db_maintenance',
        'schedule': crontab(hour=3, minute=0),  # Every day at 3:00 AM
    },
    'sync-all-mail-accounts': {
        'task': 'mail.sync_all_accounts',
        'schedule': 120.0,  # Every 2 minutes
    },
}
